### ISSUE TITLE
raise_for_status does not raise

### ISSUE THREAD

**Issue by nsmgr8** [getsentry/responses#125]
I have the following code:

`def get_url():`
  `resp = reqeusts.get(url)`
  `resp.raise_for_status()`

which I am trying to test with:

`wtih self.assertRaises(AssertionError):`
`with responses.mock as rsps:`
`rsps.add(responses.GET, url, status=404)`
`get_url()`

This does not pass and says `AssertoinError: not raised`.

   

`

**Comment by eightnoteight** [comment]
it will raise a HTTPError, not AssertionError

![screenshot from 2016-09-03 00-03-11](https://cloud.githubusercontent.com/assets/6435796/18214306/e1832486-7169-11e6-8752-7bc1a2f0d7be.png)
