### ISSUE TITLE
Please release to PyPi

### ISSUE THREAD

**Issue by nessita** [getsentry/responses#133]
Hi! I'm looking forward to many of the fixes in master that are not in the released version 0.5.1.
Is there any chance you could release a new point release soon?

Thank you.

**Comment by bluefish6** [comment]
+1

**Comment by yq314** [comment]
+1

**Comment by dz0ny** [comment]
@dcramer Any input on why this isn't released into pypa?

**Comment by FelixSchwarz** [comment]
@dz0ny If I understand the changes correctly there is no official 0.6.0 release yet. The version number was just changed after the 0.5.1 release.

**Comment by jaap3** [comment]
For reference, as of now the only *functional* changes between 0.5.1 and the current master come from these pull requests: #100, #129, #132, #139

If you happen to depend on any of these changes (for instance, I depend on #100) then the easy workaround is to just install from github and check PyPI every now and then to see if a 0.6 (or 0.5.2) has been released.

**Comment by dAnjou** [comment]
I think this can be closed → https://pypi.org/project/responses/
