### ISSUE TITLE
PY3.5: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead

### ISSUE THREAD

**Issue by bluefish6** [getsentry/responses#134]
While running responses in Python 3.5 environment, I can see now a DeprecationWarning.

```
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
```

I know this is not critical at the moment, but may be a major issue in the future when Python 3.6 will be more popular (stable 3.6.0 release is available since 23.12.2016).

**Comment by Axik** [comment]
Still unresolved and failing on major last release of 3.6 :(

**Comment by emilyjacob96** [comment]
Hi,

Am I doing something wrong? I know the problem was putting my images and
assignment on the Issue page instead of the Response page which I recently
switched to. But I don't know if I really did it.

Emily
