### ISSUE TITLE
TypeError: _on_request() takes exactly 3 arguments (8 given)

### ISSUE THREAD

**Issue by MathMagique** [getsentry/responses#138]
I use `responses` while testing a few calls to a REST API. Calls to the REST API are made using `requests.HTTPAdapter.send()` (https://github.com/kennethreitz/requests/blob/master/requests/adapters.py#L375)

Mocking these requests with `responses` fails (at least when I have not prepared responses) with the following error message:

```
adapter = <requests.HTTPAdapter object at 0x105a8b890>
request = <PreparedRequest [GET]>, a = (False, None, True, None, None)
kwargs = {}

    def unbound_on_send(adapter, request, *a, **kwargs):
>       return self._on_request(adapter, request, *a, **kwargs)
E       TypeError: _on_request() takes exactly 3 arguments (8 given)
```
`unbound_on_send` is located in `responses`. The values for parameter `a` are the (default) parameters passed to `HTTPAdapter.send()`.

These are the relevant lines in `responses`:
* https://github.com/getsentry/responses/blob/master/responses.py#L297 (call with expanded arguments)
* https://github.com/getsentry/responses/blob/master/responses.py#L231 (callee does not support extra positional arguments)

**Comment by beliaev-maksim** [comment]
@MathMagique 
can you please provide a snippet to reproduce the issue?

if issue is not reproducible on latest master, please consider closing this issue

**Comment by beliaev-maksim** [comment]
@markstory 
please close the issue

it is unclear how to reproduce. While we have an example of custom adapter running:
https://github.com/getsentry/responses/blob/5084e3f4b903c14a8c619b6b7dba4bc01d127aa4/responses/test_responses.py#L783

**Comment by hakjoon** [comment]
Let me know if its better to open a new issue.

I am running into this with the 0.1.3.0 release of [CacheControl](https://pypi.org/project/CacheControl/) it seems to only occur if you explicitly pass the arguments that `HTTPAdpater.send` if you just pass along `*args, **kwargs` it all seems to work.

Here is an adapted test based on the [existing custom adapter test](https://github.com/getsentry/responses/blob/master/responses/tests/test_responses.py#L804).  It demonstrates the difference between the two calling patterns.

```python
import requests
import responses
from responses.tests.test_responses import assert_response


def test_passing_custom_adapter():
    @responses.activate
    def run():
        url = "http://example.com"
        responses.add(responses.GET, url, body=b"test")

        calls = [0]

        class DummyAdapter(requests.adapters.HTTPAdapter):
            def send(self, *a, **k):
                calls[0] += 1
                return super().send(*a, **k)

        # Test that the adapter is actually used
        session = requests.Session()
        session.mount("http://", DummyAdapter())

        session.get(url, allow_redirects=False)
        assert calls[0] == 1

        # Test that the response is still correctly emulated
        session = requests.Session()
        session.mount("http://", DummyAdapter())

        resp = session.get(url)
        assert_response(resp, "test")

    run()


def test_breaking_custom_adapter():
    @responses.activate
    def run():
        url = "http://example.com"
        responses.add(responses.GET, url, body=b"test")

        calls = [0]

        class DummyAdapter(requests.adapters.HTTPAdapter):
            def send(self, request, stream=False, timeout=None, verify=True, cert=None, proxies=None):
                calls[0] += 1
                return super().send(request, stream, timeout, verify, cert, proxies)

        # Test that the adapter is actually used
        session = requests.Session()
        session.mount("http://", DummyAdapter())

        session.get(url, allow_redirects=False)
        assert calls[0] == 1

        # Test that the response is still correctly emulated
        session = requests.Session()
        session.mount("http://", DummyAdapter())

        resp = session.get(url)
        assert_response(resp, "test")

    run()
```

The environment is 

```
requests==2.31.0
responses==0.23.1
```

**Comment by beliaev-maksim** [comment]
@hakjoon 
please open the new issue https://github.com/getsentry/responses/issues/new?assignees=&labels=&projects=&template=bug_report.yml

and add traceback and all relevant info
If all the sufficient info will be present, then I can have a look ASAP
