### ISSUE TITLE
interaction between `assert_all_requests_are_fired` and multiple requests

### ISSUE THREAD

**Issue by thomir** [getsentry/responses#142]
Currently, if `assert_all_requests_are_fired` is set to True (the default), then the match is removed after each successful request, which has the effect that you cannot use the same mock more than one - forcing you to use each mock _exactly once_, rather than _at least once_.

I think the behaviour is non-obvious. To my mind, `assert_all_requests_are_fired` should assert if some mocks were not matched, but should not prevent mocks from being matched more than once in a single session.

**Comment by verkaufer** [comment]
Agreed. I have to interact with an API that isn't well-designed and started running into this issue when going from `0.5.1` to `0.8.1` (though this change was introduced in `0.7.0`). I usually need to make requests to the same API endpoint more than once during a given test and `assert_all_requests_are_fired` is causing issues.

There should be a flag we can switch on/off without using the `with` context functionality.

**Comment by jilljenn** [comment]
I don't know why, but if I make sure that first responses are recorded, then requests are fired, then it works. See https://github.com/mangaki/mangaki/pull/659/files#diff-e987ac4695114f0a48801440c6a628ddR181

**Comment by beliaev-maksim** [comment]
@markstory 
this is not valid for the latest version of `responses`
now we just check `call_count`

https://github.com/getsentry/responses/blob/4c4b46be0c425656017c1774495c9426ed3b5ba2/responses/__init__.py#L823


please close
