### ISSUE TITLE
Return None or False from add_callback to prevent match

### ISSUE THREAD

**Issue by dgouldin** [getsentry/responses#144]
I'd like to be able to choose whether a response is treated as a match or not using the callback function rather than just the url. How would you feel about supporting a return value of `None` or `False` (or even raising an exception) from the callback function to indicate that responses shouldn't treat it as a match?

**Comment by beliaev-maksim** [comment]
@dgouldin 
can you try adding body with exception?
~~~python
import responses
import requests

@responses.activate
def test_simple():
    responses.add(responses.GET, 'http://twitter.com/api/1/foobar',
                  body=Exception('...'))
    with pytest.raises(Exception):
        requests.get('http://twitter.com/api/1/foobar')

~~~

**Comment by beliaev-maksim** [comment]
@markstory 
this is either achievable with `passthru` or with `Exception` in the body

please close
