### ISSUE TITLE
future feature request - ability to mock exceptions with a response

### ISSUE THREAD

**Issue by jvanasco** [getsentry/responses#152]
I don't think this is possible in the current library, so for the future, it would be nice to be able to mock exceptions that have a response attribute.

As an example...

We have a flow of redirects:

    A -> 301 redirect -> B
    B -> 301 redirect -> C
    C -> 301 redirect -> D
    D -> 200 html

And I need to mock a ConnectionError, or otherwise, on C.

In a real-world situations, the error raised by `requests` has a `response` attribute, which will have the `.url` and `.history` attributes which can be inspected.  This information is unfortunately gone under `responses`.

I don't see this as being possible in the current design. It's probably not possible at all.  I did want to note this as a wishlist item if anyone ever has an idea.

**Comment by beliaev-maksim** [comment]
@jvanasco 
can you please provide a code snippet without `responses` and what you desire to have

I will check if we can add this in current lib

**Comment by kbakk** [comment]
I guess I had a little less experience with `responses`, it wasn't possible then, or I misread the issue. But I would like something like this to work:

```py
import requests, responses, pytest

@responses.activate
def test_simple():
    responses.add(
        responses.GET,
        'http://example.com/1',
        status=301,
        headers={"Location": "http://example.com/2"}
    )
    responses.add(
        responses.GET,
        'http://example.com/2',
        status=301,
        headers={"Location": "http://example.com/3"}
    )
    responses.add(
        responses.GET,
        'http://example.com/3',
        body=requests.ConnectionError("Fake error")
    )
    with pytest.raises(requests.ConnectionError) as exc_info:
        requests.get('http://example.com/1')
    assert exc_info.value.args[0] == "Fake error"
```

It appears to work 🙂 

I see in the [README.md](https://github.com/getsentry/responses/blob/master/README.rst) that there are no mentions of redirect – maybe that's why this issue was upvoted?

**Comment by beliaev-maksim** [comment]
@kbakk 
I see the issue now, thanks
it is not inability to raise an exception but an ability to redirect, right?

**Comment by kbakk** [comment]
Both are possible today/supported as demonstrated with my example. I think having an example in the docs on how to simulate redirects would be helpful.

I do see that OP is asking for the exceptions to be richer. My example don't contain the properties that request would add to the exception - especially the request and response objects. Today, it seems one have to construct the exception to have it yourself, before passing it as with the body arg.
