### ISSUE TITLE
Unexpected behavior with `match_querystring`

### ISSUE THREAD

**Issue by bcongdon** [getsentry/responses#156]
I'm noticing some strange behaviour in 0.6.0 with `match_querystring`. Here is a minimal working example.

In some tests that I write, I want to have URLs that support requests with and without querystring arguments. I was able to do this in 0.5.1, but it seems to not be possible in 0.6.0.

I have limited experience with `responses`, so let me know if this is intended behaviour.

```python
import responses
import requests


@responses.activate
def test_querystring_without_match():
    responses.add(responses.GET, 'http://foo.com', body='bar')
    responses.add(responses.GET, 'http://foo.com?query=foo', body='baz', match_querystring=True)
    print requests.get('http://foo.com').content  # prints 'bar'
    print requests.get('http://foo.com?query=foo').content  # prints 'bar', but I would expect 'baz'


@responses.activate
def test_querystring_with_match():
    responses.add(responses.GET, 'http://foo.com', body='bar', match_querystring=True)
    responses.add(responses.GET, 'http://foo.com?query=foo', body='baz', match_querystring=True)
    print requests.get('http://foo.com').content  # prints 'baz', but I would expect 'bar'
    print requests.get('http://foo.com?query=foo').content  # prints 'baz'

test_querystring_without_match()
test_querystring_with_match()
```

**Comment by dcramer** [comment]
On the first one, I'd sort of expect the behavior (given the order of registration), though it's not ideal.

The second seems like a bug, as I would expect 'bar' and then 'baz', and I'm going to take a look.
