### ISSUE TITLE
KeyError exception for mock response with status=422

### ISSUE THREAD

**Issue by dmulter** [getsentry/responses#158]
Mocking a response with a return status of 422 causes a KeyError exception with the latest version of Responses 0.6.0:

```bash
File "/project_foo/.virtualenv/lib/python2.7/site-packages/responses.py", line 234, in get_response
    reason=six.moves.http_client.responses[status],
KeyError: 422
```

Note that line 235 and 267 get friendly HTTP status code text for the status value, but the following Python code fails with KeyError:

```python
import six
six.moves.http_client.responses[422]
```

Should probably generically handle all status values that aren't available for text mapping. This is currently breaking a number of my tests.

**Comment by dcramer** [comment]
This was fixed in https://github.com/getsentry/responses/pull/164
