### ISSUE TITLE
Upgrading to 0.6.0 results in "unexpected keyword argument 'adding_headers'"

### ISSUE THREAD

**Issue by edmorley** [getsentry/responses#159]
Hi!

Upgrading from responses 0.5.1 to 0.6.0 results in the following for us:
```
TypeError: __init__() got an unexpected keyword argument 'adding_headers'
```

Was this breakage expected? It was just surprising to us given this wasn't a major version bump and the removal isn't mentioned in the release notes.

Many thanks :-)

Travis log:
https://travis-ci.org/mozilla/treeherder/jobs/260556107#L773

Usage of `adding_headers`:
https://github.com/mozilla/treeherder/blob/aff2152a810b5d68d17252669185aca9f34d28bd/tests/test_utils.py#L260-L262

**Comment by dcramer** [comment]
@edmorley definitely not expected. I rewrote it in the classes to be 'headers' instead of 'adding_headers', and I must've slipped up somewhere as the intention was to maintain the legacy path of 'adding_headers' as well.

**Comment by edmorley** [comment]
Many thanks :-)
