### ISSUE TITLE
Issues with Unicode in path

### ISSUE THREAD

**Issue by loganrosen** [getsentry/responses#175]
I saw that you fixed #153 by handling Unicode characters in the querystring, but there still appear to be issues when said Unicode characters are in the URL path itself. If you pass a mock URL with a Unicode character in it to Responses and then request the same URL via Requests, you get a connection refused error.

[This is the line](https://github.com/getsentry/responses/blob/master/responses.py#L166) where it fails, when I stepped through the debugger.

I'm using Python 2.7.13 and Responses 0.8.0. Please let me know if I need to clarify this issue. Thanks!

**Comment by kathawala** [comment]
This is happening because the `requests` library will accept a URL with unicode in it and the resulting `response.url` will be in escaped unicode, making it hard to compare the originally passed URL to the `repsonse.url`.

For example

    >>> import requests
    >>> r = requests.get('https://hi.wikipedia.org/wiki/दिलवाले_दुल्हनिया_ले_जाएंगे')
    >>> r.url
    'https://hi.wikipedia.org/wiki/%E0%A4%A6%E0%A4%BF%E0%A4%B2%E0%A4%B5%E0%A4%BE%E0%A4%B2%E0%A5%87_%E0%A4%A6%E0%A5%81%E0%A4%B2%E0%A5%8D%E0%A4%B9%E0%A4%A8%E0%A4%BF%E0%A4%AF%E0%A4%BE_%E0%A4%B2%E0%A5%87_%E0%A4%9C%E0%A4%BE%E0%A4%8F%E0%A4%82%E0%A4%97%E0%A5%87'

A workaround looks tricky, since you ideally want the user to be able to write something like this:

    import requests
    import responses

    @responses.activate
    def test_simple():
        responses.add(responses.GET, 'https://hi.wikipedia.org/wiki/दिलवाले_दुल्हनिया_ले_जाएंगे',
                      status=200)

        resp = requests.get('https://hi.wikipedia.org/wiki/दिलवाले_दुल्हनिया_ले_जाएंगे')

        assert len(responses.calls) == 1
        assert responses.calls[0].request.url == 'https://hi.wikipedia.org/wiki/दिलवाले_दुल्हनिया_ले_जाएंगे'
        assert responses.calls[0].response.status_code == 200

    test_simple()

and have it pass
