### ISSUE TITLE
Disable or deactive responses when running tests

### ISSUE THREAD

**Issue by Hultner** [getsentry/responses#184]
I've tried looking through the documentation and code but haven't found any feature allowing me to temporarily deactivate responses completely and let responses run through. 

**Background:**
I'm building a couple of small services and using responses to mock requests between them during development so a developer doesn't need to have the full suite of services running.

**Problem:**
When integrating the code with the rest of the systems I actually want these requests to go through, testing the full suite of services as a system.

**Ideal solution:**
It would be great if I could somehow (i.e. run pytest with a special flag) disable responses completely through all my tests for one run thus letting the requests propagate to the other services.

Is this at all possible at this time and if not is it something you've considered adding?

**Comment by kathawala** [comment]
Quickly looking at the documentation for `pytest`, it seems like something you can do yourself by just having versions of your tests which don't use `responses` and only running those tests when you pass a certain flag to `pytest`.

From the `pytest` documentation: https://docs.pytest.org/en/latest/example/parametrize.html

**Comment by Hultner** [comment]
@kathawala Wouldn't it require large amounts of duplication to have otherwise identical tests as both a version with and without responses. 

Could I somehow disable the whole library at one place? Then I suppose it would be quite easily implemented.

**Comment by kathawala** [comment]
There are other ways to do it, which avoid duplication and which `pytest` can allow for. Even if `pytest` did not allow for this, you could program your tests to use `responses` conditionally based on a flag.

The `pytest_generate_tests` hook seems like the best solution for you: https://docs.pytest.org/en/latest/parametrize.html#pytest-generate-tests

**Comment by carloshorn** [comment]
@Hultner, I think #400 introduced the feature you were looking for.
In your tests, you could create your response objects and add lines like this:
```python
[...]
my_response = Response(my_method, my_url, **my_other_kwargs)
if PASSTHROUGH:
    my_response.passthrouh = True
responses.add(my_response)
[...]
```
A possible and very convenient way to set such a `PASSTHROUGH` variable could be using environment variables which you can check using `os.getenv`. Then you just need to specify it in your test environment, e.g. in you `tox.ini` file you could add a line like
```
[testenv:integration]
setenv = PASSTHROUGH = true
```
