### ISSUE TITLE
cookies pkg has a deprecation warning

### ISSUE THREAD

**Issue by bcail** [getsentry/responses#186]
If you run a test script that just does "import responses" with the -Werror option, a DeprecationWarning exception is raised from the cookies package.

I'm not sure the cookies package is really maintained anymore (last commit in Sep 2014): https://gitlab.com/sashahart/cookies/commits/master. Maybe the biscuits pkg would be helpful? https://gitlab.com/sashahart/cookies/issues/4#note_50409121.

**Comment by dcramer** [comment]
If someone wants to try to swap it out thats probably fine, but to me its a not a huge concern. You can always filter out warnings from the responses package if need be.

**Comment by jsheedy** [comment]
I created pull request https://github.com/getsentry/responses/pull/218 which uses biscuits on Python 3 and continues to use cookies on Python 2.
