### ISSUE TITLE
Unable to intercept vendored requests

### ISSUE THREAD

**Issue by wimglenn** [getsentry/responses#188]
The path to the requests adapter is [hardcoded](https://github.com/getsentry/responses/blob/11e870728a30ca31885373bcbacb11fc32783a4d/responses.py#L564):

    self._patcher = mock.patch('requests.adapters.HTTPAdapter.send',
                               unbound_on_send)

However many projects vendor `requests`, and so their network activity just flies straight past the `RequestsMock` unnoticed.  To give an example, pip uses a vendored requests session and responses can not mock it out unless source code is modified with the correct mock location:

    self._patcher = mock.patch('pip._vendor.requests.adapters.HTTPAdapter.send',
                               unbound_on_send)

Could you add the requests path as configurable in the public API somehow?  Thanks!

**Comment by QasimK** [comment]
This is also an issue if you use your own `HTTPAdapter`:(

**Comment by thiagokokada** [comment]
@wimglenn I have a use case similar to you and I am trying to understand how can I use a vendored version of requests in a project. Can you give some examples?
