### ISSUE TITLE
testing against bad servers - no slash on bare domain

### ISSUE THREAD

**Issue by jvanasco** [getsentry/responses#194]
i need to test a `requests` client against some real-life edge cases with "bad servers" and have run  into some problems with how `responses` handles routes.

one of the issues i've tracked down so far is the inability to redirect to a url without a leading slash in the path

To illustrate:

This is not a valid redirect target: `http://example.com?redirectUrl=http://example.com/a`

it must be: `http://example.com/?redirectUrl=http://example.com/a`

Is there any way to easily get around this without creating multiple routes?

**Comment by beliaev-maksim** [comment]
@jvanasco 
in this case I think you need just to use `urlparse` and `urlunparse`

```python
from urllib.parse import (
        urlparse,
        urlunparse,
    ) 

url = r"http://example.com/?redirectUrl=http://example.com/a"
urlparse(url)
# >> ParseResult(scheme='http', netloc='example.com', path='/', params='', query='redirectUrl=http://example.com/a', fragment='')


url = r"http://example.com?redirectUrl=http://example.com/a"
urlparse(url)
# >>> ParseResult(scheme='http', netloc='example.com', path='', params='', query='redirectUrl=http://example.com/a', fragment='')
```

and just check that if `query` is present and `not path` , then you either append path or raise an error

current library provides mocking of responses, but syntax check is out of scope

**Comment by beliaev-maksim** [comment]
@markstory 
please close this one
