### ISSUE TITLE
Multiple of the same headers not handled, nor cookies

### ISSUE THREAD

**Issue by cgthayer** [getsentry/responses#200]
Wanted to mock a situation where I get back a few cookies, however this isn't possible because the headers arg is a dict (only one key allowed). It's typical to get multiple headers for the same name such as 'Set-Cookie' in my case.

A couple solutions come to mind (a) for cookies use the RequestsCookieJar (b) allow the values for the headers dict to be a list of strings instead of just a string (which would work for all headers, not just cookies).

Thanks,

Somewhat related
* https://github.com/getsentry/responses/issues/120
* https://github.com/getsentry/responses/issues/68

**Comment by adamdavis40208** [comment]
Also moving to CookieJar would allow us to mock cookie attributes like HttpOnly, Secure.

**Comment by retracile** [comment]
PR #285 should address these problems.  Feedback appreciated.

**Comment by markstory** [comment]
Closing as #285 was merged.
