### ISSUE TITLE
different GET params different MOCK, but still the first one's data returned

### ISSUE THREAD

**Issue by andilabs** [getsentry/responses#203]
Inside one test case I add two responses for GET with different url in terms of GET params.

1) https://maps.googleapis.com/maps/api/geocode/json?latlng=52.212917394179335,20.983095079636158&key=key

2) https://maps.googleapis.com/maps/api/geocode/json?latlng=52.20212145989611,21.006183521756945&key=key

what happens?

my test case inside in class overriden by django.test.TestCase looks like:

```
@responses.activate
def test_address_is_updated_correctly_when_spot_location_changed(self):
    latitude_1, longitude_1 = 52.226297, 20.982749
    url = REVERSE_GEOCODING_URL.format(
        latitude=latitude_1,
        longitude=longitude_1,
        api_key=settings.GOOGLE_MAP_API_KEY
    )
    responses.add(
        responses.GET,
        url,
        body=json.dumps(RESPONSE_GEOCODING_MOCK_2),
        content_type="application/json"
    )
    s1 = SpotFactory(
        name='test',
        location=Point(longitude_1, latitude_1)
    )
    s1.save()
    street_before = s1.address_street
    self.assertEqual(street_before, 'Kolejowa')
    latitude_2, longitude_2 = 52.27904, 20.980366
    url2 = REVERSE_GEOCODING_URL.format(
        latitude=latitude_2,
        longitude=longitude_2,
        api_key=settings.GOOGLE_MAP_API_KEY
    )
    responses.add(
        responses.GET,
        url2,
        body=json.dumps(RESPONSE_GEOCODING_MOCK),
        content_type="application/json"
    )
    # optionally IPDB here and done requests.get(url2) and got responses with RESPONSE_GEOCODING_MOCK_2
    s1.location.coords = (longitude_2, latitude_2)
    s1.save()
    s1 = Spot.objects.get(pk=s1.pk)
    self.assertEqual(s1.address_street, 'Mickiewicza')
```
firs assert is OK

the second one FAILS

because, the response is from the old one mock.

DEBUG: see the place optionally IPDB here and done requests.get(url2) and got responses with RESPONSE_GEOCODING_MOCK_2

When doing first time request I get (RESPONSE_GEOCODING_MOCK_2):

> ipdb> import requests; requests.get(url2).json()
> {'status': 'OK', 'results': [{'geometry': {'bounds': {'southwest': {'lat': 52.2261726, 'lng': 20.9823615}, 'northeast': {'lat': 52.22673450000001, 'lng': 20.9833889}}, 'viewport': {'southwest': {'lat': 52.22510456970851, 'lng': 20.9815262197085}, 'northeast': {'lat': 52.22780253029151, 'lng': 20.98422418029151}}, 'location': {'lat': 52.2263065, 'lng': 20.9828941}, 'location_type': 'ROOFTOP'}, 'place_id': 'ChIJW6aw25vMHkcRxgIq9iMcxA8', 'types': ['establishment', 'point_of_interest', 'premise'], 'formatted_address': 'Kolejowa 47, 01-210 Warszawa, Poland', 'address_components': [{'types': ['street_number'], 'short_name': '47', 'long_name': '47'}, {'types': ['route'], 'short_name': 'Kolejowa', 'long_name': 'Kolejowa'}, {'types': ['political', 'sublocality', 'sublocality_level_1'], 'short_name': 'Wola', 'long_name': 'Wola'}, {'types': ['locality', 'political'], 'short_name': 'Warszawa', 'long_name': 'Warszawa'}, {'types': ['administrative_area_level_2', 'political'], 'short_name': 'Warszawa', 'long_name': 'Warszawa'}, {'types': ['administrative_area_level_1', 'political'], 'short_name': 'mazowieckie', 'long_name': 'mazowieckie'}, {'types': ['country', 'political'], 'short_name': 'PL', 'long_name': 'Poland'}, {'types': ['postal_code'], 'short_name': '01-210', 'long_name': '01-210'}]}]}

when doing it for second time I get (RESPONSE_GEOCODING_MOCK):

> ipdb> import requests; requests.get(url2).json()
> {'status': 'OK', 'results': [{'geometry': {'viewport': {'southwest': {'lat': 52.2776733197085, 'lng': 20.9792990197085}, 'northeast': {'lat': 52.2803712802915, 'lng': 20.9819969802915}}, 'location': {'lat': 52.2790223, 'lng': 20.980648}, 'location_type': 'ROOFTOP'}, 'place_id': 'ChIJxXoMrOfLHkcRBAFsrjKGcMc', 'types': ['street_address'], 'formatted_address': 'Mickiewicza 74, Warszawa, Poland', 'address_components': [{'types': ['street_number'], 'short_name': '74', 'long_name': '74'}, {'types': ['route'], 'short_name': 'Mickiewicza', 'long_name': 'Mickiewicza'}, {'types': ['political', 'sublocality', 'sublocality_level_1'], 'short_name': 'Żoliborz', 'long_name': 'Żoliborz'}, {'types': ['locality', 'political'], 'short_name': 'Warszawa', 'long_name': 'Warszawa'}, {'types': ['administrative_area_level_2', 'political'], 'short_name': 'Warszawa', 'long_name': 'Warszawa'}, {'types': ['administrative_area_level_1', 'political'], 'short_name': 'mazowieckie', 'long_name': 'mazowieckie'}, {'types': ['country', 'political'], 'short_name': 'PL', 'long_name': 'Poland'}]}]}
>

**Comment by dcramer** [comment]
If you wouldn't mind throwing up a PR with a test case I imagine myself or someone else could try to make a quick bugfix

**Comment by PClmnt** [comment]
Was there ever any movement on this? Seeing the same issue.

**Comment by msaizar** [comment]
Make sure you use `match_querystring=True` if you're using GET params in your URL.

**Comment by pnuckowski** [comment]
Hi @andilabs 
To fix that test you have to move all your `responses.add()` to the top of your test. This seams to be good in terms of `when,given,then`. 

The test does not work because of the way how `responses` implements feature "multiple responses".
If you look at the [`responses source code`](https://github.com/getsentry/responses/blob/master/responses.py#L520) you can see how it's done.

In short:
Particular mocked url **must** match to multiple `responses` objects (those from `_matches` list) and only then the first matching object is returned (as regular request) and also removed from `_matches` list.

I hope it helps :)

**Comment by jaraco** [comment]
I was able to replicate the issue with [this simple test](https://gist.github.com/jaraco/13038365bfc1f17c65b2b27dc0bf87a8). Run that with `pip-run -- -m pytest foo.py` and the test will fail. Adding `match_querystring=True` to the first response solves the issue. Interestingly, the code works fine on `responses<0.10` and only starts failing on responses 0.10.

**Comment by beliaev-maksim** [comment]
taking gist provided I see that this is expected behavior
either `match_querystring` or better to use **recommended** `matchers.query_param_matcher`  method, this will work: 
~~~python
import requests
import responses
from responses.matchers import query_param_matcher

@responses.activate
def test_paginated_request():
    responses.add(
        responses.GET,
        'https://service.test/api/paginated/',
        json=dict(
            objects=[1, 2, 3],
            meta=dict(next='/api/paginated/?start=4'),
        ),
        match=[
            query_param_matcher({})
        ]
    )
    responses.add(
        responses.GET,
        'https://service.test/api/paginated/?start=4',
        json=dict(
            objects=[4, 5, 6],
        ),
        match=[
            query_param_matcher({"start": "4"})
        ]
    )
    requests.get('https://service.test/api/paginated/')
    doc = requests.get('https://service.test/api/paginated/?start=4').json()
    assert doc['objects'] == [4, 5, 6]


test_paginated_request()
~~~

@markstory 
I think this one could be closed
