### ISSUE TITLE
Feature idea: snapshots

### ISSUE THREAD

**Issue by HeyHugo** [getsentry/responses#206]
Hello, what do you think about a response snapshot feature?

Rougly it could work something like this:
```python
responses.add_snapshot(
    responses.GET,
    'http://twitter.com/api/1/foobar',
    cache_path='optional/path/to/cached/response'
)
```

First time it would make a real request and save the response to a file in the tests folder (or optionally some other path). Subsequent calls would use the cached response.

I'm not sure if there is some response info that would be hard to store, or something else I'm not thinking of otherwise I think this could enable some lazy testing 😎

**Comment by dcramer** [comment]
There are other libraries that work this way and its not a goal of responses to ever execute real requests. It creates situations where you need to have things like real API credentials coupled into a test suite and in my personal opinion is not a good generic practice. If it is something you want I'd suggest taking a look at similar libraries.
