### ISSUE TITLE
Requesting a URL, then changing the response will return the old response

### ISSUE THREAD

**Issue by rbu** [getsentry/responses#212]
The documentation states:
> You can also add multiple responses for the same url: ....

However, this is not true if you interleave adding and requesting responses:
```py
>>> import responses
>>> import requests
>>> 
>>> responses.start()
>>> 
>>> responses.add(responses.GET, "https://example.com/",
...     json={'response': 'old'}
... )
>>> requests.get('https://example.com/').content
b'{"response": "old"}'
>>> 
>>> responses.add(responses.GET, "https://example.com/",
...     json={'response': 'new'}
... )
>>> 
>>> 
>>> requests.get('https://example.com/').content
b'{"response": "old"}'
>>> requests.get('https://example.com/').content
b'{"response": "new"}'
>>> requests.get('https://example.com/').content
b'{"response": "new"}'
```

Expected result: After adding the "new" response, a "new" response is returned in the subsequent request.

Requests version: '2.19.1', Python 3.6.6

**Comment by niksite** [comment]
It seems, the feature got broken around 0.6.1 release. It is working on 0.6.0.

**Comment by rbu** [comment]
@niksite This is interesting, I went back to commit 4c9039118438205dc35c6e64db2990b7a7890e51 (which is part of version 0.5.0) and still saw this behavior. If you have a 0.6.0 environment that does not expose it, could you share the versions of other packages installed (```pip freeze```) and Python runtime version?

I used this script to test, but without a known good revision it's not possible to bisect:
```py
import sys

try:
    import responses
    import requests

    responses.start()

    responses.add(responses.GET, "https://example.com/",
        json={'response': 'old'}
    )
    assert b'{"response": "old"}' == requests.get('https://example.com/').content

    responses.add(responses.GET, "https://example.com/",
        json={'response': 'new'}
    )

    response = requests.get('https://example.com/')
    if b'{"response": "new"}' == response.content:
        sys.exit(0)
    else:
        print('Got response %r' % response.content)
        sys.exit(1)

except Exception as e:
    print(e)
    sys.exit(125)
```

**Comment by pb-jeff-oneill** [comment]
For me, in some situations the interleaving works fine and in others I get the error described here.  This was driving me crazy...  I'm surprised the bug exists 2 years later.
