### ISSUE TITLE
Wheel missing for responses 0.10.0

### ISSUE THREAD

**Issue by edmorley** [getsentry/responses#219]
Hi!

The new 0.10.0 release is currently published as just an sdist:
https://pypi.org/project/responses/0.10.0/#files

...compared to 0.9.0, which was available as both an sdist and a wheel:
https://pypi.org/project/responses/0.9.0/#files

@markstory, please could the wheel be published too?
ie: Repeating the same publish step, except this time using the `bdist_wheel` command rather than `sdist`.

Many thanks :-)

**Comment by markstory** [comment]
>  ie: Repeating the same publish step, except this time using the bdist_wheel command rather than sdist.

I can't repeat the deploy step as it is managed by travis-ci, but I can try and get another release published with sdist and wheels.

**Comment by edmorley** [comment]
Ah didn't realise automated. The fix in #220 looks correct - many thanks!
