### ISSUE TITLE
Cannot get dynamic response to work

### ISSUE THREAD

**Issue by pcolmer** [getsentry/responses#232]
I'm trying to write a test for the following piece of code:

    def process_mfa_totp(self, endpoint, url, statetoken):
        totp_response = self._requests_session.post(
            url,
            headers={'Content-Type': 'application/json',
                     'Accept': 'application/json'},
            data=json.dumps({'stateToken': statetoken,
                             'passCode': response})
        )
        totp_parsed = json.loads(totp_response.text)

where self._requests_session = requests_session. The above is only a small part of the code to highlight the problem I'm having.

Here is the start of my test code:

    @responses.activate
    def test_process_mfa_totp():
        def post_callback(request):
            payload = json.loads(request.body)
            assert payload["stateToken"] == "statetoken"
            assert payload["passCode"] == "123456"
            resp_body = {'sessionToken': "sessiontoken"}
            return (200, {}, json.dumps(resp_body))

        responses.add_callback(
            responses.POST, "http://url",
            callback=post_callback,
            content_type="application/json"
        )

        process_mfa_totp("endpoint", "http://url", "statetoken")

However, when I then call the code under test, the `json.loads` statement fails with `TypeError: the JSON object must be str, bytes or bytearray, not 'Mock'`.

I'm concerned that my callback code isn't actually being called. For example, if I put:

    assert True == False

in the callback, it doesn't fail at that point.

What am I misunderstanding?

**Comment by fdemmer** [comment]
the `response` variable, that you use in the `data` of the `post` call of `process_mfa_totp` is undefined.

after fixing that (set it to "123456" like in the assert), removing `self` from the function args, replacing `self._requests_session.post` with using `requests.post` directly the test incl responses mocking works for me.

btw: the paretheses around the `post_callback` return values is unnecessary and the `endpoint` argument of `process_mfa_totp` is unused.

so i _think_ you are not misunderstanding how things are supposed to work, but the error is from something other you have not posted and is unrelated to responses. good luck :)

**Comment by pcolmer** [comment]
Thanks, @fdemmer. I think I ended up completely rewriting the test code but it all works now.
