### ISSUE TITLE
"%2E" in url leads to ConnectionError

### ISSUE THREAD

**Issue by kelvan** [getsentry/responses#233]
It seems responses and requests do unescaping differently

**Comment by kelvan** [comment]
sorry, commited to fast
I have an url with "%2E" (".") in it, when trying to mock it doesn't match and tries to connect to the url (which isn't accessible from my dev machine)
I worked around the issue by replacing it with a ".", but maybe there are other edge cases where the unescaping works different

**Comment by markstory** [comment]
Could you provide an example mock and request that fail to pair up?

**Comment by kelvan** [comment]
```
@responses.activate
    def test_simple(self):
        import requests
        url = 'http://url.tld/foo%2Ebar'
        responses.add(responses.GET, url,
                      json={'error': 'not found'}, status=404)

        resp = requests.get(url)

        assert resp.json() == {"error": "not found"}

        assert len(responses.calls) == 1
        assert responses.calls[0].request.url == url
        assert responses.calls[0].response.text == '{"error": "not found"}'
```

**Comment by kelvan** [comment]
I'm using:
requests==2.7.0
responses==0.10.4

**Comment by markstory** [comment]
While `.` does present problems `=/[]()` did not. Because `.` doesn't strictly require to be URL encoded I'm not sure this needs needs to be solved. I've added a test covering the other characters.
