### ISSUE TITLE
Documentation update; dynamic URLs

### ISSUE THREAD

**Issue by r0fls** [getsentry/responses#242]
I don't see anything about handling dynamic URLs in the documentation. Is that supported? For example, in the Gitlab API endpoint here the `:id` is dynamic:

```
https://gitlab.example.com/api/v4/groups/:id/members
```

Will I just need to hardcode something?

**Comment by markstory** [comment]
> Will I just need to hardcode something?

You can use [regular expression patterns](https://github.com/getsentry/responses/blob/master/README.rst#response-parameters) in your response definitions.
