### ISSUE TITLE
PUT works differently with pytest than other method

### ISSUE THREAD

**Issue by sakariholvi** [getsentry/responses#251]
When testing with pytest, only the PUT method works as I expected. See the following code:

```python
import requests
import responses

url = 'http://foo.bar'
body = b'my body'


@responses.activate
def test_calls():
    responses.add(responses.GET, url, body=body)
    responses.add(responses.PUT, url, body=body)
    responses.add(responses.POST, url, body=body)

    assert requests.put(url, data='spam').content == body
    assert requests.post(url, data='spam').content == body
    assert requests.get(url).content == body


def test_without_activate():
    with responses.RequestsMock() as rsps:
        rsps.add(responses.GET, url, body=body)
        rsps.add(responses.PUT, url, body=body)
        rsps.add(responses.POST, url, body=body)

        assert requests.put(url, data='spam').content == body
        assert requests.post(url, data='spam').content == body
        assert requests.get(url).content == body
```

The first assert in both functions passes, but others do not: instead of bytes I get MockResponse objects like this:

`AssertionError: assert <MockResponse name='mock.content' id='139874595444272'> == b'my body'`

 A similar set-up worked fine when I used the standard library unittest module.

Versions I am using:
responses==0.10.5
requests==2.20.1
pytest==3.9.3
Python 3.6.6

**Comment by markstory** [comment]
I wasn't able to reproduce this problem in with python 3.6, pytest 3.10 and current master of responses.

**Comment by beliaev-maksim** [comment]
@sakariholvi 
do you still see the issue with latest version?

**Comment by beliaev-maksim** [comment]
@markstory 
please close.

Here are the results from the test run on latest master:
![grafik](https://user-images.githubusercontent.com/51964909/149962213-2c97f31f-ffd9-4d05-a4ec-cbd1bed87eb5.png)
