### ISSUE TITLE
View/modify registered responses?

### ISSUE THREAD

**Issue by ptink** [getsentry/responses#252]
I get the sense that I'm not using the library correctly but I have a list of several "default" responses that I want to be registered for most test cases. I'm using the `ResponsesMixin` from [here](https://github.com/getsentry/responses/issues/31) but this comes with its own set of issues for example if I want to override just one of the registered responses for a test there doesn't seem to be a good way to do that- also I could not find a way to inspect the list of all currently registered responses inside a test.

Is this sort of behavior outside the scope of this project or is it possible and the documentation could be expanded to include this?

**Comment by markstory** [comment]
You can modify the list of mocked responses in a few ways. You can use `replace()` to overwrite an existing mock, and `remove()` to remove a mock based on method and URL. Lastly you can use `clear()` to reset all mocks. There aren't any public APIs for looking at the currently connected mocks.
