### ISSUE TITLE
Add responses.__version__

### ISSUE THREAD

**Issue by zborboa-g** [getsentry/responses#255]
Add `__version__` attribute to `responses` so that `responses.__version__` returns the module's version.

Example implementation is available in the requests library (https://github.com/requests/requests/).
- Create `responses/__version__.py` that contains `__version__ = ...`
- In `responses/__init__.py` import `__version__`: `from .__version__ import __version__`
- In `responses/setup.py` read `__version__.py` and use when calling `setup()`

https://github.com/requests/requests/blob/master/requests/__version__.py
https://github.com/requests/requests/blob/master/requests/__init__.py
https://github.com/requests/requests/blob/master/setup.py

**Comment by beliaev-maksim** [comment]
@markstory 
I believe that this one could be closed according to comments in #332
