### ISSUE TITLE
responses.calls[n].request.body does not replicate the request body

### ISSUE THREAD

**Issue by dalepotter** [getsentry/responses#261]
I'm getting an unexpected behaviour when calling the `request.body` on a `responses.Call` object as it seems the request payload is being unpacked.

```
import requests
import responses

@responses.activate
def test_foo():
    url = 'http://foo.com/v1/ap1'
    responses.add(responses.POST, url, body='999999', status=200)

    requests.post(url, data={'123': 'abc'})

    assert len(responses.calls) == 1
    assert responses.calls[0].request.body == {'123': 'abc'}
```

I would expect a pass, but instead...

```
E       AssertionError: assert '123=abc' == {'123': 'abc'}
E        +  where '123=abc' = <PreparedRequest [POST]>.body
E        +    where <PreparedRequest [POST]> = Call(request=<PreparedRequest [POST]>, response=<Response [200]>).request
```

This is using:

requests (2.20.1)
responses (0.10.5)

Perhaps I'm missing something - should the request payload be being unpacked?

**Comment by markstory** [comment]
Are you sure the body is being unpacked? It looks like it has been serialized into a query string which seems correct based on the request's content type. Responses mocks the internal urllib3 adapter and doesn't see the request body before its been serialized.

**Comment by beliaev-maksim** [comment]
@dalepotter 
I think new matchers functionality will serve your needs:
`matchers.urlencoded_params_matcher` or `matchers.json_params_matcher`
see README

if that fixes, please consider closing this issue

**Comment by beliaev-maksim** [comment]
@markstory,
no reply here, I think also could be closed
