### ISSUE TITLE
Docker API Connection refused when running pytest

### ISSUE THREAD

**Issue by vkartik97** [getsentry/responses#265]
I am working on an application where I am using Docker to push and image:
```python
    .
    .
    .
    docker_client = docker.from_env()
    a = docker_client.containers.list()                 #Error on this line
```
I am getting 
```
<Result ConnectionError('Connection refused: GET http+docker://localhost/v1.35/containers/json?limit=-1&all=0&size=0&trunc_cmd=0',)>.exit_code
```
 when running 
```sh
$ py.test -s --cov . --cov-config .coveragerc
```
but is working perfectly when executing using `$ python file.py`

This issue seems due to using responses in tests.
How do I add exception to all requests to `http+docker`?

**Comment by markstory** [comment]
Sounds like you need to [enable a passthru](https://github.com/getsentry/responses#passing-thru-real-requests)
