### ISSUE TITLE
How to use with async/await?

### ISSUE THREAD

**Issue by vangorra** [getsentry/responses#279]
I an async test function is used, pytest no longer knows how to await the function. I suspect the response.active wrapper is assuming this is a normal function. How can we get around this? 

```python
import responses
import requests

@responses.activate
async def test_simple():
    responses.add(responses.GET, 'http://twitter.com/api/1/foobar',
                  json={'error': 'not found'}, status=404)

    resp = requests.get('http://twitter.com/api/1/foobar')

    assert resp.json() == {"error": "not found"}

    assert len(responses.calls) == 1
    assert responses.calls[0].request.url == 'http://twitter.com/api/1/foobar'
    assert responses.calls[0].response.text == '{"error": "not found"}'
```

Resulting error:
```
test_init.py::test_simple
  /home/rvangork/Documents/git/home-assistant/venv/lib/python3.7/site-packages/_pytest/python.py:178: RuntimeWarning: coroutine 'test_simple' was never awaited
    testfunction(**testargs)
```

**Comment by markstory** [comment]
You can use the [context manager](https://github.com/getsentry/responses#responses-as-a-context-manager) instead.

**Comment by mattskinosix** [comment]
Hi, 
Thank you so much for your work.
I have the same problem in my test.
Is possible to resolve di issue without using context manager?

**Comment by beliaev-maksim** [comment]
@mattskinosix 
can you check if https://github.com/beliaev-maksim/responses/tree/mbeliaev/async solves your issue?

**Comment by mattskinosix** [comment]
> @mattskinosix can you check if https://github.com/beliaev-maksim/responses/tree/mbeliaev/async solves your issue?

Yes, It works like charm.
Thank you
