### ISSUE TITLE
How to verify that response is never called without triggering AssertionError: Not all requests have been executed?

### ISSUE THREAD

**Issue by pgodzin** [getsentry/responses#287]
I want to verify in a test that a request is never even made:

```
rsps.add(responses.GET, video_segments_url, json={}, status=200)
...
assert len(rsps.calls) == 0
```
However, at the end of the test, the responses library throws `AssertionError: Not all requests have been executed` since the added response was never called.

Is there a good way to clear the list of responses expected to be executed to avoid the AssertionError?

**Comment by pgodzin** [comment]
I was able to make this work by passing in this parameter to the request mock: `responses.RequestsMock(assert_all_requests_are_fired=False)`

**Comment by markstory** [comment]
Sounds like you found a solution.
