### ISSUE TITLE
responses 0.10.8 introduces an implicit dependency on urllib3>=1.23

### ISSUE THREAD

**Issue by ksolan** [getsentry/responses#289]
responses 0.10.8 introduces these blocks:
https://github.com/getsentry/responses/blob/2d5d9f5ec33f168f097bb92f99243f18f264184c/responses.py#L382-L386

The `msg` param was not introduced until urllib3 1.23. 

`requests` itself permits any `urllib3>=1.21.1,<1.26,!=1.25.0,!=1.25.1`. If `responses` is run in an env with `urllib3<1.23`, this error gets thrown: 
```
    def get_response(self, request):
        if self.body and isinstance(self.body, Exception):
            raise self.body
    
        headers = self.get_headers()
        status = self.status
        body = _handle_body(self.body)
    
        # The requests library's cookie handling depends on the response object
        # having an original response object with the headers as the `msg`, so
        # we give it what it needs.
        orig_response = HTTPResponse(
            body=body,  # required to avoid "ValueError: Unable to determine whether fp is closed."
            msg=headers,
>           preload_content=False,
        )
E       TypeError: __init__() got an unexpected keyword argument 'msg'
```

Perhaps these new blocks can be modified to avoid `msg`? ~~Or a hard requirement for urllib3>=1.23 could be added to the responses setup.py?~~

**Comment by markstory** [comment]
How would adding/updating a pin to urllib help when importing from the version of urllib3 that is vendored into requests?

**Comment by ksolan** [comment]
Fair point, looks like all the request-vendored urllib3 versions are pre-1.23, so setting a urllib3 cap in setup.py wouldn't fix this issue if someone's using one of those.

This issue is still possible with #288. Even though requests 2.22.0 *allows* for urllib3>=1.23, it doesn't require it, and older urllib3 versions can be used. I think the best approach is finding a way to avoid the `msg` arg.

**Comment by markstory** [comment]
@ksolan The `msg` argument was the solution to multiple cookies not working. Pinning both requests and urllib higher so that broken deps don't happen as often.

**Comment by alexanian** [comment]
Good point that the pin in https://github.com/getsentry/responses/pull/288 doesn't guarantee a fix.

You could maybe do an explicit check for `version.parse(urllib3.__version___) < version.parse('1.23')` using `packaging.version` in the first import. That said, I think pinning it directly is much more straightforward.
