### ISSUE TITLE
Responses is not intercepting requests

### ISSUE THREAD

**Issue by octsobral** [getsentry/responses#305]
So, basically I am facing a weird issue with my tests. It seems like responses is not intercepting any request. The strange thing is that I tried the same test (same git commit) in another computer with the same OS, same responses version, and it does work.

Any recommendation on debugging it?

**Comment by markstory** [comment]
Use pdb, responses is python code at the end of the day.

**Comment by beliaev-maksim** [comment]
@markstory 
no snippet to debug or reproduce

propose to close
