### ISSUE TITLE
Allow applying @responses.activate to a class

### ISSUE THREAD

**Issue by piotrkilczuk** [getsentry/responses#31]
Right now I have to apply the decorator to every method I want to mock responses in; I'd prefer to apply the decorator only to the `TestCase` declaration as my `TestCase` does http in every test method. This would keep requests consistent with the mock.patch behaviour.

E.g.:

```
@responses.activate
class CommandHandlerTestCase(unittest.TestCase):

    def test_function_1(self):
        responses.add(...)

    def test_function_2(self):
        responses.add(...)

    def test_function_3(self):
        responses.add(...)
```

**Comment by bhoomit** [comment]
@droope I'm looking for the same thing. Where do I put your code?

**Comment by droope** [comment]
Hi bhoomit,

It's a decorator, usage is as follows:

<pre>
@decallmethods(responses.activate)
class BaseTests(BaseTest):
</pre>

Please see https://github.com/droope/droopescan/blob/master/dscan/tests/base_tests.py for an example.

Ta,
Pedro

**Comment by bhoomit** [comment]
Hi Pedro, 

I did it the same way as you have done here. Putting it in a module and importing it. 

    TypeError: unbound method test_firstTest() must be called with NoneType instance as first argument (got nothing instead)

The only difference with my code is that I'm extending unittest.Testcase

    @decallmethods(responses.activate)
    class ViewTests(unittest.TestCase):

What am I doing wrong here?

Thanks,
Bhoomit

**Comment by droope** [comment]
Hi bhoomit,

I am unsure why it does not work for you. We are extending different classes because I am using cement (a framework for cli apps.)

I am happy to modify my code if you find it to be the ultimate culprit.

Ta,
Pedro

**Comment by droope** [comment]
Heh, funny story, my tests started to fail with the same error you mention
above.

I put the following line before the setattr of my class decorator:

<pre>
print(cls, name, decorator, m, decorator(m))
</pre>

And got the following output:
*0.3.0:*
(<class 'dscan.tests.base_http_tests.BaseHttpTests'>, 'test_add_slash_to_urls', <bound method RequestsMock.activate of <responses.RequestsMock object at 0xb5b7aa8c>>, <unbound method BaseHttpTests.test_add_slash_to_urls>, <function test_add_slash_to_urls at 0xb5b96144>)
*0.4.0:*
(<class 'dscan.tests.base_http_tests.BaseHttpTests'>, 'test_add_slash_to_urls', <bound method RequestsMock.activate of <responses.RequestsMock object at 0xb5bcaa6c>>, <unbound method BaseHttpTests.test_add_slash_to_urls>, <unbound method NoneType.test_add_slash_to_urls>)

This means there's been a modification to the return values of
responses.activate [between responses 0.3.0 and 0.4.0](https://github.com/getsentry/responses/commit/96d36d1457724823e76367de6b4c69ddd7b7907a), which is fair enough.

I've temporarilly resolved this by only supporting responses 0.3.0, although I might look into it again in the future.

**Comment by vigneshsarma** [comment]
Using `metaclass` for decorating seems to solve the issue @droope and @bhoomit are facing

```python
def class_decorating_meta(prefix, *decorators):
    '''
    modified from: http://stackoverflow.com/a/6308016
    '''
    class DecoratingMetaclass(type):
        def __new__(self, class_name, bases, namespace):
            for key, value in list(namespace.items()):
                if not key.startswith(prefix):
                    continue
                if not callable(value):
                    continue
                for decorator in decorators:
                    value = decorator(value)
                namespace[key] = value

            return type.__new__(self, class_name, bases, namespace)

    return DecoratingMetaclass
```

Usage:
```python
class TestStuff(TestCase):
    __metaclass__ = class_decorating_meta(
        'test_',
        responses.activate)

    def test_one(self):
        pass
```

**Comment by shaiguitar** [comment]
@vigneshsarma Has your solution been verified to work for python 3.4? Seems like it worked in 2 but fails silently on 3.

**Comment by vigneshsarma** [comment]
@shaiguitar 
It seems the metaclass syntax has changed in python3. 

http://stackoverflow.com/questions/17237857/python3-singleton-metaclass-method-not-working

for this to work in python3, you have to rewrite `TestStuff` class like
```python
class TestStuff(TestCase, metaclass=class_decorating_meta(
        'test_',
        responses.activate)):

    def test_one(self):
        pass
```

**Comment by asfaltboy** [comment]
Just wanted to share how I solved this, using a mixin class, that uses TestCase  setUp and tearDown to mimic the __enter__ and __exit__ behavior of responses, and adds an (optional) default response.

```python
import responses


class ResponsesMixin(object):
    def setUp(self):
        responses._default_mock.__enter__()
        self.add_default_response()
        super(ResponsesMixin, self).setUp()

    def tearDown(self):
        super(ResponsesMixin, self).tearDown()
        responses._default_mock.__exit__()

    def add_default_response(self):
        """ Override to add default response/s for all test runs """
        pass
```

@dcramer let me know if you would like a PR of this, i.e with tests and docs

**Comment by danihodovic** [comment]
@markstory Could we include the mixin class above in the source?

**Comment by markstory** [comment]
@danihodovic Possibly. We have been trying to keep the surface area of responses small. I will check in with some of the other maintainers.

**Comment by markstory** [comment]
@danihodovic This mixin is similar in scope to [pytest-responses](https://github.com/getsentry/pytest-responses) are you using a non-pytest runner for your tests?

**Comment by danihodovic** [comment]
I work on multiple Python projects and some of them use [unittest](https://docs.python.org/3/library/unittest.html) from the standard library. While responses has a great pytest fixture, it doesn't provide anything for setup/teardown when using unittest.

**Comment by bblanchon** [comment]
Even if this mixing doesn't end up in the library, it should at least be in the documentation.
