### ISSUE TITLE
CallbackResponse is deleted when there is more than one match with a HTTP request

### ISSUE THREAD

**Issue by alanoe** [getsentry/responses#310]
Although it has a confusing name, the internal _matches list keeps the list of registered (URL,method) tuples which must be mocked (aka CallbackResponses). Each element of this list is added by calling addCalback() and should never be automatically removed. 

However, this is exactly what is done
in https://github.com/getsentry/responses/blob/bda22ade2b263ed8706e277664d95137d690c728/responses.py#L629 , if the URL regex and method of more than one CallbackResponse matches the URL and method of a HTTP request.

**Comment by markstory** [comment]
Closing as the discussion can continue in the pull request.
