### ISSUE TITLE
Inside vagrant vm... "Connection refused"

### ISSUE THREAD

**Issue by anentropic** [getsentry/responses#32]
I'm getting "Connection refused" error from requests, and this seems to prevent responses from returning its fake response.

I have:

```
    responses.add_callback(responses.GET, 'http://google.com',
                           callback=mycallback)
```

If I inspect `responses.calls._calls` I can see:

`Call(request=<PreparedRequest [GET]>, response=ConnectionError(u'Connection refused: http://google.com/',))`

so responses is activated ok and has caught the request

**Comment by xor-xor** [comment]
I've got bitten by this behavior too... But it's not limited to VMs, though - I was able to reproduce this on host OS as well.
