### ISSUE TITLE
Headers aren't added to response

### ISSUE THREAD

**Issue by XenGi** [getsentry/responses#325]
Ahoi,

I'm trying to add headers to a response but can't figure out why it doesn't work. I tried these ways:

```python
url = 'https://example.com/?cursor='
resp_body = [{'foo': 'bar'}, ]

responses.add(
    responses.Response(
        method='GET',
        url=url,
        json=resp_body,
        status=200,
        headers={
            'Link': f'<{ url }>; rel="first", <{ url }next_cursor>; rel="next"'
        },
        content_type='application/json'
    )
)
responses.add(
    responses.GET,
    url=f'{ url }next_cursor',
    json=resp_body,
    adding_headers={
        'Link': f'<{ url }>; rel="first", <{ url }prev_cursor>; rel="prev"'
    },
    status=200
)
```

In both cases the response returned in the code has only 1 header which is `{'Content-Type': 'application/json'}`. Am I doing something wrong?

I stepped through the responses code with a debugger and everything seems to work fine. The Response object gets created with the right headers but when the requests module is called it doesn't get them back.

here are my versions:
- Python: 3.8.3
- pytest: 5.4.3
- requests: 2.23.0
- responses: 0.10.14

**Comment by hramezani** [comment]
Hi @XenGi , I tried it with below example and I got the headers.

```python
url = 'https://example.com/'
resp_body = [{'foo': 'bar'}]

@responses.activate
def test_header():
    responses.add(
        responses.GET,
        url=url,
        json=resp_body,
        adding_headers={
            'Link': 'test'
        },
        status=200
    )

    resp = requests.get(
        url,
        headers={'Link': 'test'},
    )
    print(responses.calls[0].request.headers)

```

**Comment by XenGi** [comment]
I guess ether you or me misunderstood something. I want the headers in the response, not in the request. The API that I connect to gives some headers back that my function then uses. In my test I use the responses module to mock these API calls so I also need to mock the headers in these responses. My request has no relevant headers.

**Comment by XenGi** [comment]
I tried everything I found. I also use `headers` exactly like you do but they are not in the response. If you look at my example above, I'm using `headers`. I also tried to use the second example but with `headers` instead of `adding_headers` but it gives me the same result.

**Comment by XenGi** [comment]
Oh man.. I'm should stop drinking and coding that late. The whole thing didn't work because I got a one off in my tests. I was looking at the wrong one the whole time. Sorry to bother you. Everything is fine.
