### ISSUE TITLE
_cookies_from_headers breaks on Python 2 if python-future is installed

### ISSUE THREAD

**Issue by 0x9fff00** [getsentry/responses#330]
(I have also reported this at PythonCharmers/python-future#564)

If [python-future](https://github.com/PythonCharmers/python-future) is installed, the `test_cookies_from_headers` test fails on Python 2 with the following error:
```
test_responses.py:1119: in test_cookies_from_headers
    cookiejar = responses._cookies_from_headers(headers)
responses.py:122: in _cookies_from_headers
    resp_cookie.load(headers["set-cookie"])
/usr/lib/python2.7/Cookie.py:643: in load
    for k, v in rawdata.items():
E   AttributeError: 'unicode' object has no attribute 'items'
```
This happens because python-future provides a `http.cookies` module which just imports the Python 2 `Cookie` module which doesn't support Unicode strings (see PythonCharmers/python-future#564 for more information). The [`_cookies_from_headers` function](https://github.com/getsentry/responses/blob/6f682b89e373cb05e5535f098bfa38cd05282382/responses.py#L117) uses the Python 3 code path because a `http.cookies` module is available, but it fails because it doesn't support Unicode strings.

**Comment by beliaev-maksim** [comment]
@0x9fff00 
can you check if #435 solves it for you?

**Comment by 0x9fff00** [comment]
I can confirm that it's solved, thanks!
