### ISSUE TITLE
Record and replay

### ISSUE THREAD

**Issue by punya** [getsentry/responses#337]
Currently, `responses` can be configured *either* to pass-through a certain request to a real server, *or* to plug in a canned (customizable) response. Could there be an additional mode that captures the real server responses at development time, but then re-uses those recorded responses when running automated tests (e.g. in CI)? This is similar to how snapshot tests work.

Such a feature could be helpful when the real server is unsuitable for automated testing because of credentials, performance, cost, or rate limits.

If there is interest, I'd be happy to help implement this if I can get some pointers 😄

**Comment by markstory** [comment]
I don't think we want to expand the scope of this project to record runtime responses. Have you considered using libraries like [betamax](https://github.com/betamaxpy/betamax)

**Comment by punya** [comment]
Thanks for the pointer, I wasn’t aware of betamax and I’ll look into it!
