### ISSUE TITLE
Adding type hints

### ISSUE THREAD

**Issue by sbdchd** [getsentry/responses#339]
I was wondering if you'd be open to adding types directly to the repo.

If not would you be okay with me adding them to the [typeshed](https://github.com/python/typeshed/)?

**Comment by markstory** [comment]
Types in this repository would be great. Having them in typeshed could make future updates harder :smile:

**Comment by sbdchd** [comment]
Would you be okay with the stubs as a separate stub file rather than using the python2 compatible type comments?

**Comment by markstory** [comment]
@sbdchd A separate type stub is ok. At some point in 2021, we'll likely drop support for py27 in new releases and a stub file should be relatively easy to inline then.
