### ISSUE TITLE
responses v0.10.16 breaks support for python version 3.4

### ISSUE THREAD

**Issue by snarahari-byte** [getsentry/responses#342]
Hello,

Addition of `urllib3>=1.25.10` in 0.10.16 ([link](https://github.com/getsentry/responses/pull/338/files)) breaks support for pyhton version 3.4 as `urllib3` stopped supporting python 3.4 from [1.25.8]( https://pypi.org/project/urllib3/1.25.8/).

You could potentially stop supporting python v3.4 in a similar way to [v3.3](https://github.com/getsentry/responses/compare/0.10.4...0.10.5#diff-2eeaed663bd0d25b7e608891384b7298R78)

**Comment by markstory** [comment]
Python 3.4 support will be dropped when 0.12.0 is released. There isn't much I can do about the already released versions having incorrect version constraints though.

**Comment by snarahari-byte** [comment]
Thanks @markstory for sorting it out. Do you have an idea when 0.12.0 will be released?

**Comment by markstory** [comment]
@snarahari-byte I released it tonight.
