### ISSUE TITLE
Incorrect import of  HTTPHeaderDict from urllib3

### ISSUE THREAD

**Issue by yarula** [getsentry/responses#357]
responses.py:  ` from urllib3.connection import HTTPHeaderDict` this one is incorrect and will lead to import error with urllib3>=1.26.0  due to this changes:

https://github.com/urllib3/urllib3/commit/16b7b332fd1b84c2d465f11d17658c1e83d3f20f#diff-542c95910a277028550d2c8943e8c49bbcb10f9af96e35d0a0eee99b8cfe9e8c

`from urllib3._colleections import HTTPHeaderDict` is more reliable because `HTTPHeaderDict` lives there

**Comment by hramezani** [comment]
There is already an issue related to this problem https://github.com/getsentry/responses/issues/354

I think we can close this one

**Comment by pquentin** [comment]
@markstory Another reason to close this: @hramezani's PR was merged :)

**Comment by yarula** [comment]
Thanks

**Comment by yarula** [comment]
already fixed
