### ISSUE TITLE
TypeError: cannot unpack non-iterable Response object

### ISSUE THREAD

**Issue by katieannbaker** [getsentry/responses#364]
On updating some of our package dependencies for a project that we're working on, we're getting the following error:

```
self = <responses.RequestsMock object at 0x108c80450>, adapter = <requests.adapters.HTTPAdapter object at 0x10943e690>, request = <PreparedRequest [GET]>
kwargs = {'cert': None, 'proxies': OrderedDict(), 'stream': False, 'timeout': None, ...}

    def _on_request(self, adapter, request, **kwargs):
>       match, match_failed_reasons = self._find_match(request)
E       TypeError: cannot unpack non-iterable Response object
```

Versions with this error:
requests==2.25.1 (looks like a pretty recent release on 12/16/20)
responses==0.12.1
moto==1.3.16
pytest==6.2.1

Versions that we had before that did not produce an error:
requests==2.24.0
responses==0.12.0
moto==1.3.16
pytest==6.2.1

Test that can reproduce this error:
```
import pytest
from moto import mock_s3

@pytest.fixture(autouse=True)
def moto_boto():
    mocks3 = mock_s3()
    # mocks3.start()
    # yield
    # mocks3.stop()


import responses
import requests

@responses.activate
def test_failure():
    responses.add(
        responses.GET,
        url='http://test_url',
        json={"key": "val"},
        status=200
    )
    r = requests.get(url='http://test_url')
```

This failure only occurs when we have instantiated a mock of any moto service (s3, sns, ses, dynamo) regardless of whether we've started it or not. Our moto version has stayed consistent and this is corrected when we pin to a historical version of requests/responses. I'm not sure if this is an issue for moto, requests, or responses, but seeing as the requests/responses changes have caused this incompatibility and as the exception is a responses exception, I wanted to start here.

**Comment by hramezani** [comment]
It's related to this issue(https://github.com/getsentry/responses/issues/358).
Here is the reason https://github.com/getsentry/responses/issues/358#issuecomment-726826358

**Comment by katieannbaker** [comment]
@hramezani Thank you so much!
