### ISSUE TITLE
Facilitate how to view the registered responses for debugging purposes

### ISSUE THREAD

**Issue by mromagnoli** [getsentry/responses#368]
Hi maintainers! This is my first issue and intent to help here 😄 

## Motivation
When writing my tests and debugging them, sometimes I want to know which are the registered responses so far since we tend to use different fixtures to add responses and we lose track of which are the URLs expected to be called before the test ends.

The documentation says that in order to get some access to them we should access them via `responses.mock._matches` which in turn, it will return the list of `Response` objects and we have to access them to have information such as the precious URL, as in:
```
[
    <responses.Response object at 0x10a121670>,
    <responses.Response object at 0x10a1216a0>,
    <responses.Response object at 0x10a1216d0>
]
```

## Suggestion
To have a method that facilitates retrieving information of which are these registered responses.

I'd suggest something like `responses.mock.show_registered(urls_only: bool = False)` and return a list of the URLs registered if `urls_only == True` or a dictionary structure nested by `method` and `url`.
For example having:
```
responses.add(
    responses.GET, "http://example.com/", body="", headers={"X-Test": "foo"}
)
responses.add(
    responses.GET, "http://example.com/", body="", headers={"X-Test": "foo"}
)
responses.add(
    responses.POST, "http://anotherdomain.com/", body={"field": "value"}
)
```
then calling `responses.mock.show_registered(urls_only=True)` would return:
```
["http://example.com/", "http://example.com/", "http://anotherdomain.com/" ]
```
or by calling just `responses.mock.show_registered()` would return:
```
{
    'GET': {
        'http://example.com/': [
            {
                'body': '',
                'content_type': 'text/plain',
                'headers': {'X-Test': 'foo'},
                'status': 200
            },
            {
                'body': '',
                'content_type': 'text/plain',
                'headers': {'X-Test': 'foo'},
                'status': 200
            }
        ]
    },
    'POST': {
        'http://anotherdomain.com/': [
            {
                'body': {'field': 'value'},
                'content_type': 'text/plain',
                'headers': None,
                'status': 200
            }
        ]
    }
}
```

## Implementation
I have already implemented this in a local branch, if you think it could be useful I can create a Pull Request for you to review it and give me some feedback.

**Comment by markstory** [comment]
I like the idea of improving the debugging experience. Could you get the debugging information you're looking for via a `__str__` method on the `responses.Response` class? That would let you output the URL, method, status code, and content_type for a response object.

**Comment by mromagnoli** [comment]
Hi Mark, sure I'll take a look at it after work today 👌
