### ISSUE TITLE
Using urlencoded_params_matcher for matching query parameters

### ISSUE THREAD

**Issue by torfsen** [getsentry/responses#371]
I'm getting started with `responses` (version `0.12.1`), and I'm trying to match query parameters. From the README, my understanding was that I could use `urlencoded_params_matcher` for that, but it seems that this (and the `match` argument of `add`) only works for POST data, but not for query args.

This is probably intended, but the documentation could be a bit clearer here.

It seems that the right way of doing what I want is to specify the query args in the URL. This is cumbersome due to the encoding, and if you mock a lot of URLs with slightly different query arg values then it gets confusing quickly. I would prefer to pass a dict instead whose content is automatically encoded (e.g. via `urllib.parse.urlencode`). Something like

```python
responses.add(
    method='GET',
    url='https://some-host/some-endpoint',
    params={
        'foo': 'bar',
        'x': 'y',
    },
)
```

which would be roughly equivalent to

```python
url = https://some-host/some-endpoint',
params = {
    'foo': 'bar',
    'x': 'y',
}
full_url = url + '?' + urlencode(params)  # construction should be more robust
responses.add(
    method='GET',
    url=full_url,
)
```

**Comment by markstory** [comment]
> From the README, my understanding was that I could use urlencoded_params_matcher for that, but it seems that this (and the match argument of add) only works for POST data, but not for query args.

Converting the `match_querystring` behavior to the new matchers is something that has come up in the past but has not been a priority because `match_querystring` implictly turns itself on if the mocked URL has a query string.

Automatically converting request parameters sounds like a good usability improvement to me.
