### ISSUE TITLE
Responses breaks when calling requests functions between add functions

### ISSUE THREAD

**Issue by Jlrine2** [getsentry/responses#374]
Python 3.8.6 responses==0.12.1

Writing a test for a function that calls requests I discovered that multiple responses only works if you add them all before making any requests calls.

Here is how I would rather write a function that tests multiple responses, however in this case the second case ends up with `response=='content'` where I expect `response=='content2'`
```py
import responses
import requests

API_URL = 'https://someapi.com/'


@responses.activate
def test_responses():
    responses.add(responses.GET, API_URL, 'content')
    response = requests.get(API_URL)
    assert response.content == b'content'

    responses.add(responses.GET, API_URL, 'content2')
    response = requests.get(API_URL)
    assert response.content == b'content2'
```
moving the second responses.add call to the top seems to fix this issue, but it would be nice to be able to set responses near the code and functions that need them.
```py
import responses
import requests

API_URL = 'https://someapi.com/'


@responses.activate
def test_responses():
    responses.add(responses.GET, API_URL, 'content')
    responses.add(responses.GET, API_URL, 'content2')

    response = requests.get(API_URL)
    assert response.content == b'content'

    response = requests.get(API_URL)
    assert response.content == b'content2'
```

**Comment by Jlrine2** [comment]
opened https://github.com/getsentry/responses/pull/375 to adress this

**Comment by lenvk** [comment]
feels like it reproduces since version 0.6 (tested it on python3.7)

**Comment by beliaev-maksim** [comment]
@markstory 
#455 fixes this issue as well

here are the results from latest master
![image](https://user-images.githubusercontent.com/51964909/148835092-77b6e957-08c3-4d9d-9dd8-3a66e6c75e30.png)
