### ISSUE TITLE
Error or better document overlapping regex matcher behaviour 

### ISSUE THREAD

**Issue by markddavidoff** [getsentry/responses#376]
### Alternate names for this issue
Alternate name: "raise error instead of silently popping when multiple matches found (or add to readme)"
Alternate name2:  remove the `# Multiple matches found.  Remove & return the first match.` in `_find_match()`

### <3
First of all, I <3 responses. SOOOO extensible and amazing, Thank You!

###  Issue
I had a huge headache using multiple callbacks with different (overlapping) regexes. I assumed that the order of the regex matches mattered so i could do something like first add specific regex callback, then add general `.*` regex callback and the first one would match the specific case and then the general callback would be the "fallback" for the urls that didn't match the specific callback.

### Why I was confused
This made sense to me as regex is not super great at "not" matches, so i expected the implementation would allow for that. 

But instead I ended up with this weird behavior where the first match would trigger my specific callback and then the rest would trigger the general callback. And then at the end if i checked the registered matchers, I'd end up with one missing.

### Workaround
I was able to get this working by modifying my "general" regex to be the opposite (negative look ahead) of my specific regex so the general would not match the specific and there was no overlap.

### Issues with workaround
- With multiple specific cases the negative case in the general regex can get complicated.
- Regex negative lookarounds are expensive and hard to write.
- Also when you are adding callbacks in multiple different places having them not overlap can get complicated as well.

### Proposed Solutions
- Raise an error when we have multiple matching regexes instead of removing them. At the very least this should cause tests to fail
- Document this behavior explicitly in the readme

**Comment by Jlrine2** [comment]
I think this is the expected behavior, if there is more than one match when a request is made, the first match is used for that request and then it is removed so that further request will use the later ones.

**Comment by markddavidoff** [comment]
I can see that it was intentional, however, i would like it to be more
explicit enough if possible.

Silently removing callback mappings may cause unexpected side effects,
where the wrong callback was called.

In the case it is caused by poor regexes (which in my xp does happen) that
overlap, it would change which callback was called and in that case the
test might pass when it should not. I would rather the test error and fail
instead.

**Comment by Jlrine2** [comment]
removing that code would completely break the way handling of multiple responses work though.

**Comment by markddavidoff** [comment]
In your case for multiple responses I do find the existing code a bit odd though after looking at it more.

If you have N matching regexes, one will be removed until there is only 1, then that 1 will stay there. If i want to rely on it for multiple responses, shouldn't it be changed to error out when you try to make N+1 callbacks but have only N regexes instead of just returning the last one again?

Either way, there are 2 conflicting use cases:
---
#### Case A - my case
callbacks:
- callback 1 to match `abc.com`
- callback 2 to match `.*`
requests:
- `abc.com` matches callback 1, callback 1 popped from callbacks list <---  want this to error our instead
- `def.com`, matches callback 2
- `ghi.com`, matches callback 2
- `abc.com` matches callback 2 <---  want this to match callback 1 instead or to error out above

---
#### Case B - case @Jlrine2 brought up
callbacks:
- callback 1 to match `abc.com`
- callback 2 to match `abc.com`
requests:
- `abc.com` matches callback 1, callback 1 popped from callbacks list
- `abc.com`, matches callback 2
- `abc.com`, matches callback 2  <-- not a fan of this, think it should error instead, but /shrug

---
Since both cases seems valid, it seems like this needs a new flag.

**Comment by Jlrine2** [comment]
hmm I don't see a great use case for use super permissive regex matches, can you link you your use case?

**Comment by markddavidoff** [comment]
Please refer to my original post for more details, basically if you want to be able to add callbacks in mixins in different places, it can be difficult to have them not accidentally conflict. lets say one is for like `example.com` and the other is `example.com/specific_page`.
