### ISSUE TITLE
Typing error: callback has incompatible type / ValueError

### ISSUE THREAD

**Issue by m-aciek** [getsentry/responses#379]
### Environment

Python 3.9.1
Reponses 0.13.1

### Steps to Reproduce

1. Updated responses from 0.13.0 to 0.13.1
2. mypy 0.812 typing check started to fail for following code:
```
    responses.add_callback(
        responses.POST,
        "…",
        callback=callback_function,
        content_type="application/json",
    )

def callback_function(
    request: PreparedRequest,
) -> tuple[int, dict[str, str], str]:
    …
        return (200, {}, json.dumps(some_structure))
```
with
```
error: Argument "callback" to "__call__" of "_AddCallback" has incompatible type "Callable[[PreparedRequest, VarArg(Any)], Tuple[int, Dict[str, str], str]]"; expected "Callable[..., str]"
```
3. After changing callback and its signature to string only, typing check passes, but test started to fail with following trace:
```
../../.pyenv/versions/registration-api/lib/python3.9/site-packages/responses/__init__.py:748: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <responses.CallbackResponse object at 0x107113700>
request = <PreparedRequest [POST]>

    def get_response(self, request):
        headers = self.get_headers()
    
        result = self.callback(request)
        if isinstance(result, Exception):
            raise result
    
>       status, r_headers, body = result
E       ValueError: too many values to unpack (expected 3)
```

### Expected Result

I would expect either typing check to pass or responses to work.

Thank you for your work on the responses project.

**Comment by tobinus** [comment]
I'm encountering this problem as well. The problem seems to be [line 206 in the type stub](https://github.com/getsentry/responses/blob/master/responses/__init__.pyi#L206), which indicates that the callback can only return `str`. However, the actual code clearly expects either an instance of `Exception` or a tuple of status, headers and body. So if your callback satisfies the type hints, responses will crash.
