### ISSUE TITLE
Provide the test data in the PyPI tarball

### ISSUE THREAD

**Issue by laarmen** [getsentry/responses#38]
Hi,

Could you please provide the data used for the tests in the tarball next time you upload to PyPI? I'm packaging responses for Debian, and would very much like to be able to run the tests when building the package.

Thanks in advance!

**Comment by lfam** [comment]
I'm working on a package for GNU Guix [0], and I agree with @laarmen and @stefanor. It's typical for the canonical source distribution to include the test suite.

Allowing packagers to run tests on the diversity of platforms we represent will help us ensure that your software works on our platform, and it will also help find your bugs before our users do.

Do you prefer packagers use the GitHub tarball instead, or is PyPi the preferred distribution?

[0]
http://www.gnu.org/software/guix/

**Comment by FelixSchwarz** [comment]
I support this request: The src tarball on pypi should contain everything from the source repository. This is what (AFAIK) most other projects on pypi do.
