### ISSUE TITLE
The constructor to Response is supposed to have 3 required parameters.

### ISSUE THREAD

**Issue by myronsonos** [getsentry/responses#380]
The constructor to Response is supposed to have 3 required parameters.  This call to the constructor of Response passes one required arguement 'self' and passes everything else as keyword args

https://github.com/getsentry/responses/blob/9005d12e340a6d5525900d1bb9b44f51f4b701cc/responses/__init__.py#L578

**Comment by myronsonos** [comment]
I thing the problem code above should be doing

self._matches.append(Response(method, url, body=body, **kwargs))

**Comment by markstory** [comment]
How does this manifest as a problem when you're using responses?

**Comment by myronsonos** [comment]
It results in a Type error when you hit this code path.

TypeError: __init__() takes at least 3 arguments (3 given)

**Comment by myronsonos** [comment]
Ok, never mind, we have an older version of responses.
