### ISSUE TITLE
[QUESTION] - Mocked calls, order matters?

### ISSUE THREAD

**Issue by myusko** [getsentry/responses#393]
Hi,

I've faced the next scenario, just imagine that we have the function that makes two API calls

```python

def api_call():
      first_call = requests.get("example.com/toys").json()
      second_call = requests.get("example.com/toys/first").json()
      
      return first_call, second_call
```

And we have the test for the `api_call` function, where we load fixture and stub the response

```python
@responses.activate
def test_api_call():
  responses.add("GET", "example.com/toys", body={"foo": "bar"})
  responses.add("GET", "example.com/toys/first", body={"bar": "foo"})

  first_call, second_call = api_call()
 assert ....
```

And here is an interesting thing we have two different API calls for different URLs, but if the order is 

```
  responses.add("GET", "example.com/toys", body={"foo": "bar"})
  responses.add("GET", "example.com/toys/first", body={"bar": "foo"})
```

It will return the same `json` body for the two different calls.

But, if the order of stub requests will be the next
```
  responses.add("GET", "example.com/toys/first", body={"bar": "foo"})
  responses.add("GET", "example.com/toys", body={"foo": "bar"})
```

It will work as expected, and the question is - order of mock responses are matters?

Thank you in advance.

**Comment by markstory** [comment]
Yes order matters.

**Comment by myusko** [comment]
@markstory Thank you for the clarification.

Probably will be helpful if it will be mentioned somewhere in the documentation.

Thank you again.
