### ISSUE TITLE
add a passthrough flag to BaseResponse

### ISSUE THREAD

**Issue by carloshorn** [getsentry/responses#399]
I am currently using *responses* to mock an API for running tests during development. However, I want to reuse these tests when sending the requests to the actual API, where I also want to use the `assert_call_count` method.
A solution could be to add the endpoints as passthru instead of mocked responses, but this would require to add the `passthru_prefixes` to the summation of `assert_call_count`.
Another solution could be a flag in the `BaseResponse` class which allows to activate a pass through callback for the matching request if the flag is set, otherwise use the predefined response. This would also make the `passthru_prefixes` obsolete, because they could be implemented as normal `Response` objects where this flag is set to `True`, so the matching logic of the normal Response instances could be reused.

I think this is somehow related to #388, because such a "passthrough on condition" as in the given example could be implemented with a `passthrough` property (or getter method) in `BaseResponse` which could be checked in `RequestsMock._on_request` to decide if the incoming request should be sent to the actual endpoint or if the response should be build from the mock data.

Many thanks for building this library. Looking forward for some feedback to the proposed feature.

**Comment by markstory** [comment]
What would an example of the usage you want to do look like? I'm having a hard time visualizing how you would reuse your mocks when also sending requests to the actual service you would make requests to.

The `passthru` feature is intended for endpoints that you don't want to have mocked responses for as once responses is active all network requests require mocks.

**Comment by carloshorn** [comment]
Let me start with a vision.

I would like to launch my whole backend (endpoints, databases, etc.) and run the test suite for my python API library (which is intended to run on the client side) that hits these endpoints. These expensive tests may run regularly on the main branch with a scheduler to check if the python API library still works with the latest version of the backend. However, on the python API library dev-branches, I do not want expensive tests, but still I want tests which come as close as possible to the real endpoints, being reproducible and not depending on availability of the real endpoints. Therefore, I would record the responses during the expensive tests. And just replay them on tests during development.

> ... how you would reuse your mocks when also sending requests to the actual service you would make requests to.
> The passthru feature is intended for endpoints that you don't want to have mocked responses for as once responses is active all network requests require mocks.

Imagine there is this passthrough flag, which I can set on the responses in my test suite depending on an environment variable for instance. If active it will not mock, but instead hit the real endpoint and ignore any given mock values. Even if this flag is set for all mocks, there is still the benefit from responses, that the test case will not allow any not defined requests (*... as once responses is active all network requests require ...*), which is a cool feature during testing by the way. Now, if I deactivate the flag (should be default) and rerun, the given `response_obj.get_response` will be returned (mock data or callback function or custom implementation).
Note, in this scenario technically speaking, the Response object is not necessarily a mock. It defines which requests are allowed and how to handle it, where one possible way of handling is to pass through, but the default way is returning mocked data. Therefore the `passthru_prefixes` would become obsolete and as beneficial side effect, it would become possible to check the call counts even for requests/responses that pass though.

If this passthrough flag would be there, the "only" step missing to the vision would be the recorder capability, which could be a json dump of the requests and corresponding responses or any other sort of serialization. This dump would be an artefact that should persist and therefore its production should not necessarily be tied to tests. It could also be created in another way. It is just necessary to have an alternative constructor for the Response object to create it from this serialization to be able to return the recorded response. Of cause, I know that this is not as straight forward as it may sound in this paragraph, because the responses may change in a CRUD API, so there could be a dependency on execution order. When thinking about simple test cases using `unittest`, this could be solved, by storing the responses in execution order per test method, but this is beyond the scope of this issue.

I hope I could clarify a bit why I think this feature could be interesting and useful. If you agree, I could open a PR where we could discuss implementation details.

**Comment by carloshorn** [comment]
After reading through other issues, I feel like this feature could also be related to #184

**Comment by markstory** [comment]
I've been thinking about this a bit more, and had some questions.

> I would like to launch my whole backend (endpoints, databases, etc.) and run the test suite for my python API library (which is intended to run on the client side) that hits these endpoints. These expensive tests may run regularly on the main branch with a scheduler to check if the python API library still works with the latest version of the backend.

Accpetance/end to end tests are outside the scope of responses, as is recording request/response pairs and the related maintenance around recordings.

> However, on the python API library dev-branches, I do not want expensive tests, but still I want tests which come as close as possible to the real endpoints, being reproducible and not depending on availability of the real endpoints. ... Imagine there is this passthrough flag, which I can set on the responses in my test suite depending on an environment variable for instance. If active it will not mock, but instead hit the real endpoint and ignore any given mock values. 

This kind of usage is where responses is a great fit. You can also do most of what you're looking for by conditionally enabling responses based on the your environment variable. For example, you could have a context manager in your client library tests that looks like

```python
def sometimes_mock(func):
    if os.environ.get("USE_REAL_NETWORK"):
        return func()
    else:
        responses.start()
        func()
        responses.stop()
```

I think this would achieve all of what you're looking for. It would also still allow you to find missing mocks in your 'fast' tests suites.

**Comment by carloshorn** [comment]
> Accpetance/end to end tests are outside the scope of responses, as is recording request/response pairs and the related maintenance around recordings.

I am aware that end to end tests are outside the scope of *responses* and I totally understand why features like recording responses should not be part of this library as outlined in the discussion in the paragraph: 
> If this passthrough flag would be there, the "only" step missing [...] but this is beyond the scope of this issue.

Such things are too use case specific and I could/should have said "beyond the scope of this library".
Still, the proposed feature would enable me to use this library as a building block for my use case of recording, where the recorder could be a subclass of `BaseResponse`. All these implementations would live in my test modules having *responses* as dependency.

Furthermore, I also think that this feature could be very beneficial to other users of this library by giving more control over passthroughs, e.g. specifying the allowed method.

**Comment by carloshorn** [comment]
@markstory, thanks for the fruitful discussion and code review.

As a short remark on my recorder plans, I just realized, that it is almost there already within the library :-).
I just need to check the `CallList` at the end of the test, e.g. in the `tearDown` method. However, I forgot to add passthrough responses to the CallList...

**Comment by markstory** [comment]
> However, I forgot to add passthrough responses to the CallList...

That sounds like a reasonable addition to make if you want to do it.

**Comment by carloshorn** [comment]
I have opened #409 to address this need.

To finalize the story of my vision and to publish what I did so others may encounter it, below is the code that enables me to do what I want. As discussed, this is a solution to a specific problem, where *responses* helped as dependency, but it may not be general enough to add it to the library.

```python
import unittest
import re
import pickle
import pathlib
import os
import zlib

import requests
import responses


# different modes
# RECORD -> record all calls
RECORD = os.getenv("RECORD") is not None
# PASSTHROUGH -> check if previously recorded requests are still representative
PASSTHROUGH = os.getenv("PASSTHROUGH") is not None

http_methods = [
    'GET',
    'HEAD',
    'POST',
    'PUT',
    'DELETE',
    'CONNECT',
    'OPTIONS',
    'TRACE',
    'PATCH'
]


class ReplayResponse(responses.Response):
    def __init__(self, request, response, stream=False,
                 match_headers_keys=None):
        self._request = request
        self._response = response
        super().__init__(
            request.method,
            request.url,
            body=response.content,
            status=response.status_code,
            headers=response.headers,
            stream=stream
        )
        if "gzip" in response.headers.get("Content-Encoding", ''):
            self.body = self._gzip_compress(self.body)

    @staticmethod
    def _gzip_compress(data):
        if hasattr(data, 'read'):
            data = data.read()
        if isinstance(data, str):
            data = data.encode()
        # window size flag, +25 to +31 include a basic gzip
        # header and trailing checksum
        wbits = 28
        compressor = zlib.compressobj(wbits=wbits)
        compressed_chunks = [
            compressor.compress(data),
            compressor.flush()
        ]
        return b''.join(compressed_chunks)


class ReplayResponsesTestCase(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.recordpath = pathlib.Path(f'{cls.__module__}.{cls.__name__}.pickle')
        cls.requests_mock = responses.RequestsMock(
            assert_all_requests_are_fired=(not RECORD)
        )
        cls.records = {} if RECORD else pickle.loads(cls.recordpath.read_bytes())
        cls.requests_mock.start()

    def setUp(self):
        if RECORD:
            url = re.compile('.*')
            for method in http_methods:
                self.requests_mock.add(
                    responses.PassthroughResponse(method, url)
                )
        else:
            calls = self.records.get(self.record_key, responses.CallList())
            for request, response in calls:
                replay = ReplayResponse(request, response)
                if PASSTHROUGH:
                    replay.passthrough = True
                self.requests_mock.add(replay)
            self.addCleanup(self.requests_mock.reset)

    def tearDown(self):
        if RECORD:
            self.records[self.record_key] = self.requests_mock.calls

    @classmethod
    def tearDownClass(cls):
        cls.requests_mock.stop()
        if RECORD:
            with cls.recordpath.open('wb') as file:
                pickle.dump(cls.records, file)

    @property
    def record_key(self):
        return self._testMethodName


class MyTest(ReplayResponsesTestCase):
    def test_google(self):
        requests.get('https://www.google.com')

    @unittest.skipIf(RECORD, "Cannot provoke server error on demand.")
    def test_server_error(self):
        self.requests_mock.add(responses.GET, 'https://example.com', status=503)
        response = requests.get('https://example.com')
        self.assertEqual(response.status_code, 503)

```

If I store this code as `test_recorder.py`, I can use the different modes
1. Record relevant calls `RECORD=1 pytest -v -k test_recorder.py`
2. Replay calls (cheap and fast) `pytest -v -k test_recorder.py`
3. Check if recorded calls are still representative (the web API may have changed) `PASSTHROUGH=1 pytest -v -k test_recorder.py`
