### ISSUE TITLE
Add expected response from a file

### ISSUE THREAD

**Issue by saaj** [getsentry/responses#40]
In your [introductory blog post](http://cramer.io/2014/05/20/mocking-requests-with-responses/) you have the last example with a lot of such calls:

```
responses.add(
            responses.GET, 'http://jenkins.example.com/job/server/2/logText/progressiveHtml/?start=0',
            match_querystring=True,
            adding_headers={'X-Text-Size': '7'},
            body='Foo bar')
```

This is clearly a lack of the feature and the workaround because it is barely practical to stuff one's test suite with big response strings. And a full response file can contain all of status, headers and response body. It can look like this (py3):

```
from io import BytesIO
from http.client import HTTPResponse

import responses


class FakeSocket():

  _stream = None


  def __init__(self, s):
    self._stream = BytesIO(s)

  def makefile(self, *args, **kwargs):
    return self._stream


def parse_response(request_string):
  response = HTTPResponse(FakeSocket(request_string))
  response.begin()
  return response

class ResponseMock(responses.RequestsMock):

  def add_from_file(self, method, url, filename, match_querystring = False, stream = False):  
    with open(filename, 'rb') as f:
      r = parse_response(f.read())

    content_type = r.getheader('content-type', 'text/plain')

    self.add(method, url, r.read(), match_querystring, r.status, r.getheaders(), stream, content_type)
```

Response file can look like this:

```
HTTP/1.1 200 OK
Date: Sat, 22 Nov 2014 12:00:40 GMT
Content-Type: text/xml; charset="utf-8"
Connection: close

Some <em>HTML</em> goes here.
```

**Comment by jackdbernier** [comment]
It would be really nice to have.

Meanwhile you can also load the content of a file and pass it to `body`

```
with open ('body.txt', 'r') as myfile:
    body = myfile.read()

responses.add(
    responses.GET, 'http://jenkins.example.com/job/server/2/logText/progressiveHtml/?start=0',
    match_querystring=True,
    adding_headers={'X-Text-Size': str(len(body))},
    body=body)
```

**Comment by codeasashu** [comment]
Nice to have feature. Additionally, I really like [wiremock stubbing](https://wiremock.org/docs/stubbing/) using json files. Json/Yaml is quite handly too when REST is considered. If we can support the json format that wiremock has, we can use same json files as is. 

If stubs are supported, any call to `responses.add` will add more requests to stubs, overwriting the stubs if request path matches.

Here is a function signature I am thinking to use:

```py
@responses.activate(stub_path="./__fixtures__/stub-request.json")
def test_request_is_sent():
     # no need to do `responses.add` since we have stubbed it with json
     requests.post(...)
     assert len(responses.calls) == 1

def test_request_is_sent_in_context():
     # same works for contexts too
     with responses.activate(stub_path="./__fixtures__/stub-request.json"):
         requests.post(...)
         assert len(responses.calls) == 1
```

What do you think @beliaev-maksim ?

**Comment by beliaev-maksim** [comment]
@codeasashu 
we have already considered this feature implementation possibility but in slightly different shape compared to one you mentioned. Similar to `vcrpy`

Once we fully finish migration from python 2 I have planned to handle this one.

**Comment by markstory** [comment]
@codeasashu @beliaev-maksim I think the direction of this interface is something we should draft up in an issue before implementing. I'll need to circulate it a bit internally at Sentry as it is a significant expansion in scope.
