### ISSUE TITLE
Searching Responses and Manipulation of Matching Order

### ISSUE THREAD

**Issue by carloshorn** [getsentry/responses#406]
## Description

Currently, the order of registered responses is only determined by the insertion order which is also the order in which a request will look for matches. #400 wants to introduce a priority attribute which provides a little more control on the matching order. However, more control over the responses within a priority group in the registry would be beneficial. It should also be possible to locate (get matching order index) a response in the registry and search for responses of some criteria.

## User Stories

    - I want to be able to specify the matching order of newly registered responses at any time, so that I do not need 
      to insert my responses in metching order.
    - I want to be able to search for registered responses, so I can more easily update or remove them.
    - I want to be able to move registered responses (without changing priority), so I can manipulate the matching
      order at any time.

### Search interface

```python
class RequestsMock:
    ...
    def search(self, resp_filter: Callable[[response], bool]) -> list[BaseResponse]:
        ...
        return responses
    ...
resp = RequestMock()
for response in my_responses:
    resp.add(respons)
index, relevant = resp.search(lambda response: response.method == responses.POST)
```

### Change Matching Order

```python
class RequestsMock:
    ...
    def move(self, response: Union[BaseResponse, int], pos: int, relative: bool = False) -> None:
        ...
    ...
resp = RequestMock()
for response in my_responses:
    resp.add(response)
last_response = my_responses[-1]
# move three position forward
resp.move(last_response, -3, relative=True)
# move in front
resp.move(last_response, 0)
# move last response in front (access by index) this might be useful if the response is registerd 
# several times, because the non-index approach should only move the first occurring response.
resp.move(-1, 0)
```
Note that this method should try to move the response to the desired location, but it might be sorted backwards because of a lower priority.
Example (only showing priority).
In `[HIGH, HIGH, NORMAL, LOW]` using `move(-1, 0)` would not change the list, because the last element is the only one with priority low, but `move(1, 0)` would swap the first two items.

### Set Matching Position Directly

```python
class RequestsMock:
    ...
    def add(self, ..., pos: Optional[int] = None) -> ...:
        ...
    ...
resp = RequestMock()
for respons in my_responses:
    resp.add(respons)
# add this response on third position (use python indexing starting with 0)
resp.add(my_other_response, pos=2)
```
Also here, the position may be sorted backwards depending on the priority.

The methods `add` and `move` could also get a flag called `force` which would overwrite the priority to enforce the desired location, but I do not know if this is needed or should be the default.

Looking forward for some feedback to the proposed feature.

**Comment by markstory** [comment]
When would you need to do this? With the focus of this library being on writing tests, when are you dynamically reordering mock responses? From my usage it is simpler to define the mock responses in the order you want the responses to be used.

**Comment by carloshorn** [comment]
I agree on searching and maybe the moving to not be very relevant in tests, but setting the position when adding the response has a simple use case. Imagine, you have a `unittest.TestCase` where you register some default responses in the `setUp` method. In the test methods, you add some test specific responses, which you want to prepend in the matching order.

The searching function might be something for test developer which need to debug cases like #376.

**Comment by carloshorn** [comment]
I have been thinking about this issue again, and I conclude that the proper type of `RequestsMock._matches` would be a `collection.deque[BaseResponse]` which could be directly exposed to the public interface. Instead of using the `RequestMock.add` method, an advanced user could directly add responses to the registry using all offered `deque` methods like `insert`, `append`, `appendleft`, `extend`, `extendleft`. The matching order manipulation could be left to the advanced user who would not feel bad about manipulating the private attribute `RequestsMock._matches`.
Another more theoretical reason for using `deque` is the fact that matches are evaluated in FIFO order and popped left, which is not a list (LIFO) use case, but "theoretical" also means that it is not a real argument for refactoring, because the total amount of items will always be small, so list will also do well here.

**Comment by carloshorn** [comment]
Let me revise my previous statement. using a `list` for the registry is good. The `_find_match` algorithm is making things more complicated than needed. A non-backward compatible solution was proposed in #311, I would like to propose a very simple algorithm which should be backward compatible for normal intended use cases which would not delete any provided response, and therefore not need any `pop` operations.

Scotch:
Loop in normal order and provide responses with `call_count == 0`. If there is no match found, loop in reverse order and provide all responses with `call_count > 0`.
