### ISSUE TITLE
Cookie handling regression from 0.14.0 to 0.15.0

### ISSUE THREAD

**Issue by retracile** [getsentry/responses#421]
### Environment

Using the responses library under Python 3.9.7

### Steps to Reproduce

Run this test against responses 0.14.0 and against responses 0.15.0

```
#!/usr/bin/env python3
import sys
import requests
import responses



def main():
    with responses.RequestsMock() as fakes:
        fakes.add(responses.GET, 'https://example.com', status=200,
            adding_headers=[
                  ('Set-Cookie', 'mycookie=myvalue; path=/; secure'),
            ],
        body="Returned body",
        )

        session = requests.session()
        response = session.get('https://example.com')

        tests = {}
        tests['response-cookie'] = 'mycookie' in response.cookies
        tests['session-cookie'] = 'mycookie' in session.cookies

        failures = 0
        for testname, result in tests.items():
            if not result:
                failures += 1
            sys.stdout.write(f"Test {testname} result {result}\n")
        if failures:
            sys.stdout.write(f"{failures} of {len(tests)} failed.\n")
        else:
            sys.stdout.write(f"All {len(tests)} tests passed.\n")

        return 1 if failures else 0

if __name__ == '__main__':
    sys.exit(main())
```

### Expected Result
Expected 'mycookie' to appear in both the response.cookies and the session.cookies

### Actual Result

'mycookie' appears in both the response.cookies and the session.cookies for 0.14.0
'mycookie' appears in the response.cookies *but not* in the session.cookies for 0.15.0

**Comment by danpalmer** [comment]
@markstory is this bugfix ready to go out? I see it in the changelog but looks like there hasn't been a release on PyPI yet.

If there's anything I can do to help get it shipped I'm happy to help out! We're in the unfortunate position of needing changes in 0.15 but depending on the session cookie handling that broke in that release.

**Comment by beliaev-maksim** [comment]
@danpalmer 
 so far you can try to install from master
`pip install git+https://github.com/getsentry/responses.git@master`

**Comment by danpalmer** [comment]
@beliaev-maksim Yeah that's an option, it's just a bit slower, less clear when we're safe to un-pin (we'd pin the commit rather than the branch) etc. Just thought I'd see whether this release is ready to go out so that everyone gets the fix.

**Comment by beliaev-maksim** [comment]
@danpalmer 
yes, if it is for a wide rollout, then it is better to wait a bit

about replacement. It depends on PyPi configs. If development (beta) packages are configured, then you will see a replacement.

**Comment by danpalmer** [comment]
This regression has been live on PyPI for a few weeks now, maybe we could publish just this bug fix as `0.15.1`? If I create a PR for that, do you think it would be accepted and released on PyPI?

**Comment by danpalmer** [comment]
> Also as far as I know (please correct me if I'm wrong) pip doesn't upgrade packages to git versions, i.e. moving from 0.14 to 50299f5 doesn't actually replace the package

Ah, just realised that the reason this isn't working is that this package still has its version specified as `0.14.0` on master. Pip is doing the right thing, it's just that this package is incorrect. I'll submit a PR.

**Comment by beliaev-maksim** [comment]
@danpalmer 
as far as I know publish is done via automated bot

**Comment by danpalmer** [comment]
@beliaev-maksim release are run manually by @markstory

**Comment by markstory** [comment]
>  as far as I know publish is done via automated bot
> releases are run manually by

It is both! Because of compliance rules, I start the release manually which is reviewed, approved and then delivered by a bot.

**Comment by markstory** [comment]
Release for 0.16 is scheduled. https://github.com/getsentry/responses/actions/runs/1449966071

**Comment by danpalmer** [comment]
@markstory thanks!
