### ISSUE TITLE
Coverage 6 is out

### ISSUE THREAD

**Issue by McSinyx** [getsentry/responses#430]
Coverage 6 has been out for a while, you might want to consider allowing it.

**Comment by beliaev-maksim** [comment]
coverage 6.0.0+ requires CPy 3.6+
so, at the moment it is incompatible

@markstory 
do we plan to drop 2.7 support?

**Comment by McSinyx** [comment]
IIUC coverage 6 requiring Python >= 3.6 means that e.g. pip will install
coverage < 6 on Python < 3.6

**Comment by markstory** [comment]
> do we plan to drop 2.7 support?

Eventually yes. Is not using coverage 6 causing problems for you @McSinyx ?

**Comment by McSinyx** [comment]
Not personally, I noticed it working on a downstream repository and thought you might want to check if the testsuite works with coverage 6.
