### ISSUE TITLE
responses 0.15.0 not setting cookies

### ISSUE THREAD

**Issue by TravisFrankMTG** [getsentry/responses#439]
### Environment

responses 0.15.0

### Steps to Reproduce

```python
from unittest import TestCase

from requests import Session
from requests.adapters import HTTPAdapter
import responses
from urllib3.util.retry import Retry


class TestSession(TestCase):

  @responses.activate
  def test_cookies_enabled_on_session(self):
    responses.add(responses.GET, "http://test.com", body="resp", status=200, headers={"set-cookie": "foo=bar"})
    sess = Session()
    retries = 1
    retry = Retry(
        total=retries,
        read=retries,
        connect=retries,
        status=retries,
        backoff_factor=0.1,
        status_forcelist=frozenset([500, 502, 504]),
    )
    adapter = HTTPAdapter(max_retries=retry)
    sess.mount("http://", adapter)
    sess.mount("https://", adapter)
    resp = sess.get("http://test.com")
    assert resp.text == "resp" # True
    assert sess.cookies.get("foo") == "bar" # False, should be True
```

Run above with `pytest`.

### Expected Result

With 0.14.0, the above test passes, which is the expected result (cookies should be set).

### Actual Result

In 0.15.0, the above test fails as the cookie are not set.

**Comment by beliaev-maksim** [comment]
please try on latest `master`

I think this might be related to #421

**Comment by chadwhitacre** [comment]
Shall we close this as a dupe?

**Comment by beliaev-maksim** [comment]
@chadwhitacre 
I will do a test on 16.0 to confirm that this one was resolved and let you know

**Comment by beliaev-maksim** [comment]
@chadwhitacre 
fixed on latest master and should be in 16.0
![image](https://user-images.githubusercontent.com/51964909/142085384-35111253-dbc3-4321-a8bf-3e4bf9b3c088.png)

**Comment by chadwhitacre** [comment]
Sweet. :)

Do you have perms to close here? Not obvious to me ...

**Comment by beliaev-maksim** [comment]
@chadwhitacre 
no, I have not :)
