### ISSUE TITLE
Incorrect setUp example in README

### ISSUE THREAD

**Issue by itsdkey** [getsentry/responses#448]
### Environment

There is a bug in the README doc in the `Responses inside a unittest setUp()` section. At the moment the docs say that you should add  stop BEFORE reset to the cleanUp functions but since cleanups are run in reversed order this is incorrect. In this configuration you won't be able to check if every mock was called since the reset will reset the responses mock's list and `stop` won't have anything to check. You can check this out by investigating the unittest.TestCase class. 

`

    def doCleanups(self):
        
        outcome = self._outcome or _Outcome()
        while self._cleanups:
            function, args, kwargs = self._cleanups.pop()
            with outcome.testPartExecutor(self):
                function(*args, **kwargs)
                
        # return this for backwards compatibility
        # even though we no longer us it internally
        return outcome.success
`

As you can see there is a `.pop()` call that pop the LAST element from the list. 
### Steps to Reproduce

1. You can reproduce this by simply doing a TestCase with 1 mocked response and changing the order of the functions added to cleanups

### Expected Result

The reset should be added to cleanups BEFORE the stop function. The docs should be:

`

    def setUp():
         self.responses = responses.RequestsMock()
         self.responses.start()

         # self.responses.add(...)

         self.addCleanup(self.responses.reset)
         self.addCleanup(self.responses.stop)
    

    def test_api(self):
        self.responses.add(
            responses.GET, 'http://twitter.com/api/1/foobar',
            body='{}', status=200,
            content_type='application/json')
        resp = requests.get('http://twitter.com/api/1/foobar')
        assert resp.status_code == 200
`

**Comment by itsdkey** [comment]
The change works but it isn't what I was thinking about. Let me give an example: when you have 50 tests in a TestCase it is easier to initialize the responses in setUp instead of decorating each test separately. Sometimes you need to arrange some 3rd party endpoint to make a flow work.

It's basically the same idea like in the mock library: https://docs.python.org/3/library/unittest.mock.html#patch-methods-start-and-stop

**Comment by beliaev-maksim** [comment]
@itsdkey
Difference between patch and responses is that for patching you provide multiple additional arguments and you may need multiple decorators for each function

While single thing you need to do here is to apply `@responses.activate`, which is explicitly shows that current test is mocked
While all `add()` methods you keep in setup

This will allow library to manage environment for you

**Comment by itsdkey** [comment]
@beliaev-maksim 
Okay, I get your point but still, your example is slightly different than mine. If you decorate each test with the `@responses.activate` decorator you won't check if each mocked URL was fired. Sometimes you want to be sure that specific endpoints are triggered in each test. To do that I put my response mocks in the setup and make sure that `self.responses.stop()` is triggered before `self.responses.reset()`. That way I'm able to test if everything when correctly.

I'll put my examples here (sorry for using DRF APITestCase but it inherits from unittest.TestCase):
 

    import requests
    import responses
    from rest_framework.test import APITestCase
    
    class TestTestCase(APITestCase):

        def setUp(self) -> None:
            responses.add(responses.GET, 'http://google.com/', body='ok')
            responses.add(responses.GET, 'http://google.com/test/', body='ok')

        @responses.activate
        def test_add_in_setup(self):
            result = requests.get('http://google.com/')

            self.assertEqual(b'ok', result.content)

        @responses.activate
        def test_add_in_setup_2(self):
            result = requests.get('http://google.com/')

            self.assertEqual(b'ok', result.content)

        @responses.activate
        def test_add_in_setup_3(self):
            result = requests.get('http://google.com/test/')

            self.assertEqual(b'ok', result.content)

        @responses.activate
        def test_not_mocked_url(self):
            result = requests.get('http://google.com/test/not-mocked/')

            self.assertEqual(404, result.status_code)

        @responses.activate
        def test_not_fired(self):
            self.assertEqual(1, 1)

    class TestTestCase2(APITestCase):

        def setUp(self) -> None:
            self.responses = responses.RequestsMock()
            self.responses.add(responses.GET, 'http://google.com/', body='ok')
            self.responses.add(responses.GET, 'http://google.com/test/', body='ok')
            self.responses.start()
            self.addCleanup(self.responses.reset)
            self.addCleanup(self.responses.stop)

        def test_add_in_setup(self):
            result = requests.get('http://google.com/')

            self.assertEqual(b'ok', result.content)

        def test_add_in_setup_2(self):
            result = requests.get('http://google.com/')

            self.assertEqual(b'ok', result.content)

        def test_add_in_setup_3(self):
            result = requests.get('http://google.com/test/')

            self.assertEqual(b'ok', result.content)

        def test_not_mocked_url(self):
            result = requests.get('http://google.com/test/not-mocked/')

            self.assertEqual(404, result.status_code)

        def test_not_fired(self):
            self.assertEqual(1, 1)

results:

    >python manage.py test app.TestTestCase

    Creating test database for alias 'default'...

    System check identified 3 issues (0 silenced).
    ....E
    ======================================================================
    ERROR: test_not_mocked_url (baits.tests.test_viewsets.TestTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "<string>", line 3, in wrapper
      File "/backend/baits/tests/test_viewsets.py", line 1633, in test_not_mocked_url
        result = requests.get('http://google.com/test/not-mocked/')
      File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
        return request('get', url, params=params, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
        return session.request(method=method, url=url, **kwargs)
     File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
        resp = self.send(prep, **send_kwargs)
     File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
        r = adapter.send(request, **kwargs)
     File "/usr/local/lib/python3.9/site-packages/responses/__init__.py", line 773, in unbound_on_send
        return self._on_request(adapter, request, *a, **kwargs)
     File "/usr/local/lib/python3.9/site-packages/responses/__init__.py", line 753, in _on_request
        raise response
    requests.exceptions.ConnectionError: Connection refused by Responses - the call doesn't match any registered mock.

    Request: 
    - GET http://google.com/test/not-mocked/

    Available matches:
    - GET http://google.com/ URL does not match
    - GET http://google.com/test/ URL does not match

    ----------------------------------------------------------------------
    Ran 5 tests in 0.026s

    FAILED (errors=1)
    Destroying test database for alias 'default'...`

And TestCase2:

    >python manage.py test app.TestTestCase2
    Creating test database for alias 'default'...

    System check identified 3 issues (0 silenced).
    FFFFEF
    ======================================================================
    ERROR: test_not_mocked_url (baits.tests.test_viewsets.TestTestCase2)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/backend/baits/tests/test_viewsets.py", line 1669, in test_not_mocked_url
        result = requests.get('http://google.com/test/not-mocked/')
      File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
        return request('get', url, params=params, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/responses/__init__.py", line 773, in unbound_on_send
        return self._on_request(adapter, request, *a, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/responses/__init__.py", line 753, in _on_request
        raise response
    requests.exceptions.ConnectionError: Connection refused by Responses - the call doesn't match any registered mock.

    Request: 
    - GET http://google.com/test/not-mocked/

    Available matches:
    - GET http://google.com/ URL does not match
    - GET http://google.com/test/ URL does not match

    ======================================================================
    FAIL: test_add_in_setup (baits.tests.test_viewsets.TestTestCase2)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/responses/__init__.py", line 788, in stop
        raise AssertionError(
    AssertionError: Not all requests have been executed [('GET', 'http://google.com/test/')]

    ======================================================================
    FAIL: test_add_in_setup_2 (baits.tests.test_viewsets.TestTestCase2)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/responses/__init__.py", line 788, in stop
        raise AssertionError(
    AssertionError: Not all requests have been executed [('GET', 'http://google.com/test/')]

    ======================================================================
    FAIL: test_add_in_setup_3 (baits.tests.test_viewsets.TestTestCase2)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/responses/__init__.py", line 788, in stop
        raise AssertionError(
    AssertionError: Not all requests have been executed [('GET', 'http://google.com/')]

    ======================================================================
    FAIL: test_not_fired (baits.tests.test_viewsets.TestTestCase2)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/responses/__init__.py", line 788, in stop
        raise AssertionError(
    AssertionError: Not all requests have been executed [('GET', 'http://google.com/'), ('GET', 'http://google.com/test/')]

    ======================================================================
    FAIL: test_not_mocked_url (baits.tests.test_viewsets.TestTestCase2)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/responses/__init__.py", line 788, in stop
       raise AssertionError(
    AssertionError: Not all requests have been executed [('GET', 'http://google.com/'), ('GET', 'http://google.com/test/')]

    ----------------------------------------------------------------------
    Ran 5 tests in 0.015s

    FAILED (failures=5, errors=1)


I think that there are two options here:
a) responses' decorator has a bug?
b) creating an instance of RequestMock and doing it manually works differently than using a decorator

So as a compromise I suggest adding two options on activating responses:
1. using the decorator and adding mocked responses in setup
2. using a RequestMock instance and adding mocked responses to it then manually calling stop and reset but adding them to _cleanups by using `self.addCleanUp(...)`

**Comment by beliaev-maksim** [comment]
@itsdkey 
```python
    def setUp(self) -> None:
        responses.mock.assert_all_requests_are_fired = True
        responses.add(responses.GET, 'http://google.com/', body='ok')
        responses.add(responses.GET, 'http://google.com/test/', body='ok')
```

**Comment by itsdkey** [comment]
okay, this can be good :smile:

**Comment by beliaev-maksim** [comment]
@itsdkey 
glad it helps :)
