### ISSUE TITLE
CallbackResponse returning different Response's body

### ISSUE THREAD

**Issue by joshua-badger** [getsentry/responses#452]
### Steps to Reproduce

1. Instantiated RequestsMock as a context manager
2. Added callback response (`response_mock.add_callback("post", "https://fake-url/url-path", callback=lambda request: (200, {}, json.dumps({"some": "result_dict_or_list"}), content_type="application/json")`)
3. Added normal response (`response_mock.add("get", "https://different-fake-url/with/another/fake/path", body={"a": ["new", "body"]}, status=200, content_type="application/json")`)
4. Called the first URL

### Expected Result

200 Response with body `{"some": "result_dict_or_list"}`

### Actual Result

200 Response with body `{"a": ["new", "body"]}`

**Comment by beliaev-maksim** [comment]
@joshua-badger 
even if the instruction is clear, we need to construct code manually and this might be different from yours

please provide a code snippet that you use, minimal reproducible.
Also, decouple `sentry` from `responses` at this moment

**Comment by joshua-badger** [comment]
Please disregard, the issue comes from how I am defining the callback. The test I constructed for `responses` passed and I could not get it to fail, and I believe I have now isolated the problem. Thank you!
