### ISSUE TITLE
@responses.activate triggers untyped decorator error in mypy

### ISSUE THREAD

**Issue by JMMarchant** [getsentry/responses#468]
### Environment

`responses==0.17.0`
`mypy==0.931`
`Python 3.8.12`

`disallow_untyped_decorators = True` in `mypy.ini`

### Steps to Reproduce

After upgrade to `responses==0.17.0`, reran `mypy` with settings unchanged from before.

### Expected Result

`mypy` passes as happened with `responses==0.16.0`

### Actual Result

Every instance of `@responses.activate` throws up:
```
error: Untyped decorator makes function "<function_name>" untyped  [misc]
    @responses.activate
```

The issue seems to be related to the change [here](https://github.com/getsentry/responses/blob/6e7d4669c1a0bb236747111fc8e9502c281d7fcf/responses/__init__.pyi#L278) where the type hint for `activate` was changed from a callback protocol to `Any`.

**Comment by beliaev-maksim** [comment]
@JMMarchant 
can you please check it on https://github.com/beliaev-maksim/responses/tree/fix_468 and confirm that the issue is gone

**Comment by JMMarchant** [comment]
Yep, that looks to have fixed it!

**Comment by beliaev-maksim** [comment]
@JMMarchant 
thanks for confirmation!

**Comment by markstory** [comment]
>  any idea why disallow_untyped_decorators did not raise on our side?

It looks like that check has been disabled in this project's mypy.ini. I can work on merging our stubs with the implementation and removing some of the disabled warnings.
