### ISSUE TITLE
Provide a py.test fixture in addition to the decorator 

### ISSUE THREAD

**Issue by ThiefMaster** [getsentry/responses#47]
When using py.test for tests it's usually nicer to activate features like this using a fixture. The usage with the fixture (assuming it's named `responses`) could be like this:

``` python
def test_my_api(responses):
    responses.add(responses.GET, 'http://twitter.com/api/1/foobar',
                  body='{"error": "not found"}', status=404,
                  content_type='application/json')

    # ...
```

I.e. instead of the decorator you'd use a `responses` fixture and instead of calling `add` as a global from the imported module (if you register it as a pytest plugin the user doesn't need to import it at all) you'd call it on the object returned by the fixture function (which could simple be the module `responses`, but a wrapper would be cleaner of course).

**Comment by hangtwenty** [comment]
:+1:

**Comment by nichochar** [comment]
:+1:

**Comment by aequitas** [comment]
Have not tested it in all situations yet, but this works for me:

```python
# conftest.py
import pytest
from responses import mock


@pytest.yield_fixture
def responses():
    rsps = mock
    rsps.start()
    yield rsps
    rsps.stop()
    rsps.reset()

```

**Comment by hangtwenty** [comment]
Seems like a good start; how to make it obvious/deterministic where to call `responses.add` though? Maybe do all of that in a `responses_setup` fixture and make the start/stop/reset fixture (`responses_activate`) depend on that?

I suppose we could KISS and put both items just in an example in the README, eh?

**Comment by greenmoon55** [comment]
:+1:

**Comment by tomviner** [comment]
Or even more simply:
```python
@pytest.yield_fixture
def http_fake():
    with responses.RequestsMock() as rsps:
        yield rsps
```

**Comment by hangtwenty** [comment]
A README addition makes sense

**Comment by edmorley** [comment]
Since pytest 3.0 `yield_fixture` is deprecated in favour of using `fixture` directly:
http://doc.pytest.org/en/latest/yieldfixture.html

ie:

```python
@pytest.fixture
def responses():
    with responses.RequestsMock() as rsps:
        yield rsps
```
