### ISSUE TITLE
regression regarding content_type in 0.10.8

### ISSUE THREAD

**Issue by jvanasco** [getsentry/responses#483]
A test started failing on an application when updating our code and testing against the current `responses`.

I traced it back to a regression in the 0.10.8 release. When there is collision between `content_type` and `adding_headers["Content-Type"]` on `responses.RequestsMock.add`

In 0.10.7 and below, the `content_type` argument is ignored if `Content-Type` is provided as a header.

In 0.10.8 and above, the `content_type` argument is prepended to  the headers' `Content-Type` when provided.

### Steps to Reproduce

An executable reproduction is provided below.

pip install "responses==0.10.7"
python {ExampleFile}.py

pip install --upgrade responses
python {ExampleFile}.py

### Expected Result

I did not expect a breaking change.

I would expect a breaking change like this to either:

* be properly listed in the changelog
* raise an exception when there is an overlap in conflicting arguments

When trying to decide workarounds, this was also noted:

When headers are computed, a "," is used to prepend the `content_type` to the `adding_headers["Content-Type"]`. This means one can not strip out "text/html" from a header that has a charset in it, and rely on Responses to upgrade it:

This is invalid:
 
     `{'Content-Type': 'text/html, charset=utf-8'}`

As this is valid 

     `{'Content-Type': 'text/html; charset=utf-8'}`

While I'd love to see the old functionality return, I understand fixing this regression may not be a priority.  Because the Content-Type generated by passing in both arguments is not RFC compliant,  I think a changlog entry is insufficient and this library would need to raise an Exception if `content_type` is specified alongside a "Content-Type" header.  

This was painful to debug.

### Actual Result

Described above.

### Executable Example

```python
# pypi
import responses
import requests

with responses.RequestsMock(assert_all_requests_are_fired=False) as rsps:
    rsps.add(
        responses.GET,
        "http://example.com/index-1.html",
        body="<html>1</html>",
        content_type="text/html",
    )
    rsps.add(
        responses.GET,
        "http://example.com/index-2.html",
        body="<html>2</html>",
        adding_headers={
            "Content-Type": "text/html2; charset=utf-8",  # html2 to differentiate against html
        },
    )
    rsps.add(
        responses.GET,
        "http://example.com/index-3.html",
        body="<html>3</html>",
        content_type="text/html",
        adding_headers={
            "Content-Type": "text/html2; charset=utf-8",  # html2 to differentiate against html
        },
    )

    r1 = requests.get("http://example.com/index-1.html")
    assert r1.headers["Content-Type"] == "text/html"
    
    r2 = requests.get("http://example.com/index-2.html")
    try:
        assert r2.headers["Content-Type"] == "text/plain, text/html2; charset=utf-8"
        print("r2 REGRESSION")
    except:
        assert r2.headers["Content-Type"] == "text/html2; charset=utf-8"
        print("r2 legacy")

    r3 = requests.get("http://example.com/index-3.html")
    try:
        assert r3.headers["Content-Type"] == "text/html, text/html2; charset=utf-8"
        print("r3 REGRESSION")
    except:
        assert r3.headers["Content-Type"] == "text/html2; charset=utf-8"
        print("r3 legacy")
```

**Comment by markstory** [comment]
> While I'd love to see the old functionality return, I understand fixing this regression may not be a priority. Because the Content-Type generated by passing in both arguments is not RFC compliant, I think a changlog entry is insufficient and this library would need to raise an Exception if content_type is specified alongside a "Content-Type" header.

Providing content_type in both places was undefined behavior, and there isn't any backwards compatibility for those kinds of scenarios.

I agree that an exception could be raised if someone tries to operate responses with those parameters.

**Comment by jvanasco** [comment]
Thanks. I hope no one else gets bit by this.

If anyone else does,  this is the fix I had deployed last week:

```
def adjust_content_type_headers(headers, content_type="text/html"):
    """
    responses 0.10.8 introduced a regression where an unforunate collision
    can take place between::

        content_type=
        adding_headers={"Content-Type":}

    see::
        https://github.com/getsentry/responses/issues/483
    
    :param headers: headers to be passed as `adding_headers`
    :type headers: dict
    :param content_type: content_type to be passed as `content_type` 
    :type content_type: str, default "text/html"
    
    usage::
    
		with responses.RequestsMock() rsps:
			...
			_headers, _content_type = adjust_content_type_headers(
				headers, content_type
			)
			rsps.add(
				...
				adding_headers=_headers,
				content_type=_content_type,
			)
    """
    _headers = headers.copy()
    if "Content-Type" in _headers:
        _components = [i.strip() for i in _headers["Content-Type"].split(";")]
        # is the content-type "text/html", a charset/etc, or both!
        if "/" in _components[0]:
            # it's a content/type
            # unset the kwarg and keep everything in the headers
            content_type = None
        elif "=" in _components[0]:
            # proobably a charset without a content-type
            # push our content type into this, and exit out
            _components.insert(0, content_type)
            content_type = None
        else:
            raise ValueError("fork if i know what this is")

        _headers["Content-Type"] = ";".join(_components)
    return (_headers, content_type)
```
