### ISSUE TITLE
Release plan for 0.17.1 or 0.18.0?

### ISSUE THREAD

**Issue by sirosen** [getsentry/responses#490]
When I first tried using `0.17.0` I ran straight into a bug (#464). I was happy to see it was already reported and being handled right away.
However, it's now been a few weeks and browsing the issue tracker gives me no clear insight into when I can expect the fix to be released.

There are a lot of ways that projects do or don't communicate their release plans, and usually it doesn't matter much. But in the particular case of there being bugfixes in `master` which are not in the latest release, as a user you want to know when to expect it.
Is there a plan for a v0.17.1 or v0.18.0 soon? Or should I check back in a while?

---

P.S. I understand and appreciate everything that goes into maintaining a package, and don't want to sound at all ungrateful. A huge thanks for `responses`! It is a godsend for testing. ❤️

**Comment by beliaev-maksim** [comment]
@markstory
I see that bot has created a branch for 0.18
When is it scheduled to publish?

**Comment by markstory** [comment]
> When is it scheduled to publish?

Looks like the publish was forgotten about. I'll nudge the folks who approve releases on our side.

**Comment by beliaev-maksim** [comment]
@markstory
Release is out, thanks
We can close the issue

**Comment by sirosen** [comment]
Thanks so much for looking into this!
