### ISSUE TITLE
Ordered Registry

### ISSUE THREAD

**Issue by ric79** [getsentry/responses#502]
Hello I just downloaded the 0.0.18 and 

from responses.registries import OrderedRegistry

is not working because it was not added to this last version even if it is documented. Are you going to deprecate this class or I have to wait until a new version?

Rr

**Comment by beliaev-maksim** [comment]
please refer to https://github.com/getsentry/responses/blob/master/CHANGES

this feature will appear in 0.19
or you can pip install from github master directly

**Comment by ric79** [comment]
Thanks! Sorry
