### ISSUE TITLE
Path segment parameters not handled correctly

### ISSUE THREAD

**Issue by mib112** [getsentry/responses#506]
URL matching does not respect path segment parameters in the last path segment. This is probably caused by using `urlparse` instead of `urlsplit` in [_get_url_and_path](https://github.com/getsentry/responses/blob/a35896e9a1690730524c68d689ff1fde269d797a/responses/__init__.py#L215).

### Environment

Python 3.9
responses 0.18.0

### Steps to Reproduce

```
import responses
import requests

mock = responses.RequestsMock(assert_all_requests_are_fired=False)

mock.add(responses.GET, 'http://example.com/here/we')
mock.add(responses.GET, 'http://example.com/here/we;go')

request = requests.Request('GET', 'http://example.com/here/we;go').prepare()
print(mock._registry.find(request))
```

### Expected Result

Match the second mocked `CallbackResponse` with path segment parameter `go`.

### Actual Result

```
(<Response(url='http://example.com/here/we' status=200 content_type='text/plain' headers='null')>, [])
```

**Comment by beliaev-maksim** [comment]
`responses` differentiates a pure URL matching and URL "parts" matching, mainly with `responses.matchers`.

However, it is not native to add such support. It is not a segment. `;` is used along with `&` to specify query parameters
unfortunately, parameters go away with python and `&` should be used for queries

you can see https://docs.python.org/3/library/urllib.parse.html#url-parsing
<html><body>


params | 3 | No longer used | always an empty string
-- | -- | -- | --



</body>
</html>


also, read about the change in 3.10
https://docs.python.org/3/library/urllib.parse.html#urllib.parse.parse_qs

semicolon is going away


I would recommend you to create a custom matcher, where you can use regex to match the part after `;`
https://github.com/getsentry/responses#creating-custom-matcher

**Comment by mib112** [comment]
Hi Maksim,
thanks for your answer.

I am talking about URL **path segment parameters (aka matrix parameters)**. This is different from **query parameters**. According to the Rfc for URLs, a path segment can contain special characters for further structuring, for example a semicolon. This should be treated as opaque generally.

The linked documentation refers to the **query parameter** separator, not the special character used for path segment structuring (in fact, the documentation for `urlparse` is very unclear what `params` even is and "always an empty string" is misleading at best - there is a [nice write-up](https://sethmlarson.dev/blog/why-urls-are-hard-path-params-urlparse) about this).

In the same documentation you'll find the following quote referring to the problem I'm pointing out here:
 
https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlsplit

> This is similar to urlparse(), but does not split the params from the URL. This should generally be used instead of urlparse() if the more recent URL syntax allowing parameters to be applied to each segment of the path portion of the URL (see RFC 2396) is wanted.

To further clarify:

```
>>> urlparse("http://example.com/segment1;param1/segment2;param2?query=value1;q2=v2")
ParseResult(scheme='http', netloc='example.com', path='/segment1;param1/segment2', params='param2', query='query=value1;q2=v2', fragment='')
```

`urlparse` does split the path segment parameter from the last path segment, which is not the desired behavior for modern url handling.

In contrast, `urlsplit` leaves the last path segment alone and delegates any necessary parsing of the parameters to a separate function (see Python doc mentioned above).

``` 
>>> urlsplit("http://example.com/segment1;param1/segment2;param2?query=value1;q2=v2")
SplitResult(scheme='http', netloc='example.com', path='/segment1;param1/segment2;param2', query='query=value1;q2=v2', fragment='')
```

The reason for this difference is (I'm guessing here), `urlparse` was intended to support path segment parameters, but it was originally forgotten that these parameters can occur in any path segment (not only in the last one). Because Python stdlib decided to not handle path segment parameters at all (see docs for `urlparse` and `urlsplit`), responses should do the same (IMO).

Of course, I can create a custom matcher to handle this, but in my opinion this is not the correct default behaviour.

**Comment by beliaev-maksim** [comment]
@mib112 
agree, RFC 3986 is very explicit about the URL path part

> The path is terminated by the first question mark ("?") or number sign ("#") character, or by the end of the URI.

I submitted the PR for the change

**Comment by mib112** [comment]
Thank you for this quick response and keep up the good work :-)
