### ISSUE TITLE
new template for `responses` issues

### ISSUE THREAD

**Issue by beliaev-maksim** [getsentry/responses#519]
@chadwhitacre @markstory 
can we set a template for `responses` issues?
currently it is more about `sentry`

we need in template:
1. version of responses
2. minimal reproducible self-contained snippet. Ready to be copy pasted and run.
3. current output
4. expected output

now it looks like:
![image](https://user-images.githubusercontent.com/51964909/158857223-6c2f5ea4-f014-4a4a-b40e-f33b21e67150.png)

**Comment by chadwhitacre** [comment]
Good call, it's using the defaults from https://github.com/getsentry/.github which aren't the best here.

Have you worked with [issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) before? Wanna make a PR? :)

**Comment by beliaev-maksim** [comment]
@chadwhitacre 
so, basically we can either use organization template or a repo template, right?

then I propose to create a repo template and locate it in https://github.com/getsentry/responses/tree/master/.github

I can create a PR
