### ISSUE TITLE
Support for chaining responses targeted at the same URL and method

### ISSUE THREAD

**Issue by mrname** [getsentry/responses#52]
I really love responses, but I had to start using HTTPretty, because I am testing against an API that always uses the same URL (ya I know....), so I have to chain the responses like this:

https://github.com/gabrielfalcao/HTTPretty#rotating-responses

Everything has been fine, but I realized that `match_querystring` does not do what you would expect. In my case, I have two of the same URL with different query strings that get called multiple times. Everything is fine on the first attempt of each, but after that, HTTPretty will just return the last result over and over (regardless of the query string).

I was wondering if responses is thinking about adding support for chaining responses (since query string matching seems to work properly in this module). I am going to work on adding this functionality to either HTTPretty or responses, and wanted to see if you guys would be interested in having such functionality.

Thanks!

**Comment by dcramer** [comment]
It seems like it'd be pretty easy

IMO though by default you wouldn't want rotating responses, so maybe its something like .add_chain() and on iter exhaustion it errors.

**Comment by mrname** [comment]
Awesome, thanks for the quick feedback brother!

**Comment by beliaev-maksim** [comment]
@mrname 
I assume doc is: https://github.com/gabrielfalcao/HTTPretty/tree/python-3.3-support#rotating-responses

if yes, then I would say if you will use `query_param_matcher` from latest version, it will resolve your issue
response will be matched by query, so each time you will get proper result based on query and not URL
