### ISSUE TITLE
Tests failed with Requests 1.2.3

### ISSUE THREAD

**Issue by curtisforrester** [getsentry/responses#54]
Might need to update the readme to refine the version requirements.

I had an older version of requests installed in my virtual env and the tests failed (example of fail below). However, upgrading to latest 2.6 requests resolved the issue. 

================================== FAILURES ===================================
________________________________ test_response ________________________________
test_responses.py:42: in test_response
    run()
<string>:3: in wrapper
    ???
test_responses.py:30: in run
    resp = requests.get('http://example.com')
..\..\pyVirtCTRAQ\lib\site-packages\requests\api.py:55: in get
    return request('get', url, **kwargs)
..\..\pyVirtCTRAQ\lib\site-packages\requests\api.py:44: in request
    return session.request(method=method, url=url, **kwargs)
..\..\pyVirtCTRAQ\lib\site-packages\requests\sessions.py:335: in request
    resp = self.send(prep, **send_kwargs)
responses.py:265: in unbound_on_send
    return self._on_request(session, requests, *a, **kwargs)
responses.py:242: in _on_request
    response = adapter.build_response(request, response)
..\..\pyVirtCTRAQ\lib\site-packages\requests\adapters.py:176: in build_response
    extract_cookies_to_jar(response.cookies, req, resp)
..\..\pyVirtCTRAQ\lib\site-packages\requests\cookies.py:108: in extract_cookies_to_jar
    res = MockResponse(response._original_response.msg)
E   AttributeError: 'NoneType' object has no attribute 'msg'

**Comment by kivikakk** [comment]
I'm hitting this also.

**Comment by dcramer** [comment]
Closing in favor of #66
