### ISSUE TITLE
How to mix `@responses.activate` and `with responses.RequestsMock`

### ISSUE THREAD

**Issue by brno32** [getsentry/responses#541]
I have a library that uses `with responses.RequestsMock` to mock everything that happens in a certain context. I've wrapped this into a decorator.

```python
import decorator

@decorator
def mock_my_api(func, *args, **kwargs):
    with responses.RequestsMock(assert_all_requests_are_fired=False) as rsps:
        rsps.add(
            responses.POST,
            terminate_regex(LOGIN_URL),
            body=SOAP_API_LOGIN_RESPONSE,
            content_type="text/xml",
        )
        return func(*args, **kwargs)

@mock_my_api
def test_stuff():
    # tests some calls to my_api
    assert True
```

This works great, but I want to mock another api, completely unrelated to my `mock_my_api` in the same test so that I can test a function that hits the endpoints from `my_api` and some other endpoint. I want to do this

```python
@mock_my_api
@responses.activate
def test_stuff():
    responses.start()
    # Get Access Code
    responses.add(
        responses.Response(
            method="POST",
            url=settings.SOME_OTHER_API,
            json={"access_token": "123"},
        )
    )
    access_code = get_access_token()

    # now make calls to my_api
```

However I get error messages like
```
E           requests.exceptions.ConnectionError: Connection refused by Responses - the call doesn't match any registered mock.
E
E           Request:
E           - POST https://myapi.com
E
E           Available matches
```

So I think `responses` isn't letting me mix the two approaches. If I'm running inside the context manager, additionally mocked calls from `responses.activate` don't work. Interesting, if I swap the order like this

```python
@responses.activate
@mock_my_api
def test_stuff():
    pass
```

then I get an error message about the other api not being patched

```
E           requests.exceptions.ConnectionError: Connection refused by Responses - the call doesn't match any registered mock.
E
E           Request:
E           - POST https://other.api.com/
E
E           Available matches:
E           - POST re.compile('https://myapi.com') URL does not match
```

So the order matters, and it looks like one approach of setting up `responses` clears out the mocks of the other

Is there a way to mix the two?

**Comment by beliaev-maksim** [comment]
we have a form for opening issues. Please fill the form instead of using blank

I do not see any minimal reproducible
https://stackoverflow.com/help/minimal-reproducible-example

please open the issue using the [form](https://github.com/getsentry/responses/issues/new?assignees=&labels=&template=bug_report.yml) and filling all the fields

**Comment by brno32** [comment]
done [here](https://github.com/getsentry/responses/issues/542). Thanks!
