### ISSUE TITLE
How to mix `@responses.activate` with `responses.RequestsMock`

### ISSUE THREAD

**Issue by brno32** [getsentry/responses#542]
### Describe the bug

I have a library that uses with `responses.RequestsMock` to mock everything that happens in a certain context. I've wrapped this into a decorator. This works great, but I want to mock another api, completely unrelated to the api being mocked in my decorator in the same test. Yet, when I do so, `responses.activate` clears the other mocks

### Additional context

I'm using `responses` in a library of mine to wrap an API I often work with. I use this library in many tests and would like to be able to use it in a test where I need to decorate the test with `responses.activate` to mock an API unrelated to the API my library wraps.

I need this to work with some decorator like `@mock_google` so that I can put the decorator in a library and import it easily elsewhere, while being able to use it in conjunction with `responses.activate`

### Version of `responses`

0.20.0

### Steps to Reproduce

```python
import responses
import requests

from decorator import decorator

GOOGLE_URL = "https://www.google.com/"
YOUTUBE_URL = "https://www.youtube.com/"


@decorator
def mock_google(func, *args, **kwargs):
    with responses.RequestsMock(assert_all_requests_are_fired=False) as rsps:
        rsps.add(responses.GET, GOOGLE_URL, json={"success": True})
        return func(*args, **kwargs)


def business_logic():
    response = requests.get(GOOGLE_URL)
    payload = response.json()
    assert payload["success"]
    response = requests.get(YOUTUBE_URL)
    payload = response.json()
    assert payload["success"]


@mock_google
@responses.activate
def test_stuff():
    responses.add(
        responses.Response(method="POST", url=YOUTUBE_URL, json={"success": True})
    )
    business_logic()
```

repo for example:
https://github.com/Kicksaw-Consulting/responses-minimal-reproducible-example

### Expected Result

I expect the test to pass and both urls to be mocked by `responses`.

### Actual Result

The test fails and I get the following error

```
E           requests.exceptions.ConnectionError: Connection refused by Responses - the call doesn't match any registered mock.
E
E           Request:
E           - GET https://www.google.com/
E
E           Available matches:
E           - POST https://www.youtube.com/ Method does not matc
```

It's clear that `@responses.activate` is erasing the mocks from my decorator

**Comment by beliaev-maksim** [comment]
thanks for the example.

Let me explain how your example works under the hood.
1. call `test_stuff`
2. our decorator creates default mock
3. you register YOUTUBE_URL under default_mock in responses
4. you wrap in `mock_google` which
   a. creates new mock `rsps`
   b. registers GOOGLE_URL under `rsps`
   c. you do not do any call to `requests`
   d. you exit `rsps`
   e. `rsps` got deleted
6. you call `business_logic`
7. you call `requests.get(GOOGLE_URL)` -> does not exist in default mock -> Fail


depending on your need one of the following chapters should help, just need to be slightly adjusted
https://github.com/getsentry/responses#integration-with-unit-test-frameworks

**Comment by brno32** [comment]
I think I disagree with point `4.c`, though. I _do_ make calls to `requests`. The following works. A request is sent out to google.com and successfully mocked.

```python
@decorator
def mock_google(func, *args, **kwargs):
    with responses.RequestsMock(assert_all_requests_are_fired=False) as rsps:
        rsps.add(responses.GET, GOOGLE_URL, json={"success": True})
        # we're still inside the context here so if func makes any calls to requests, it'll check the mock
        return func(*args, **kwargs)


def business_logic():
    response = requests.get(GOOGLE_URL)
    payload = response.json()
    assert payload["success"]


@mock_google
def test_stuff():
    responses.add(
        responses.Response(method="POST", url=YOUTUBE_URL, json={"success": True})
    )
    business_logic()
```

Since my function is run within the context manager in the `@mock_google` decorator, it grabs the requests. I suppose my question is, is there a way to check multiple mocks or combine the mock I manually created in `@mock_google` with the default mock? Why does attaching `responses.activate` clear the mock from `@mock_google`?

**Comment by beliaev-maksim** [comment]
@brno32 
why do you think it clears another mock? it does not

first straight away question, why just not to add another URL to `default_mock` ?
```python
import responses
import requests

from decorator import decorator

GOOGLE_URL = "https://www.google.com/"
YOUTUBE_URL = "https://www.youtube.com/"


@decorator
def mock_google(func, *args, **kwargs):
        responses.get(GOOGLE_URL, json={"success_gg": True})
        return func(*args, **kwargs)


def business_logic():
    response = requests.get(GOOGLE_URL)
    payload = response.json()
    assert payload["success_gg"]
    response = requests.post(YOUTUBE_URL)
    payload = response.json()
    assert payload["success_yb"]


@mock_google
@responses.activate
def test_stuff():
    responses.post(url=YOUTUBE_URL, json={"success_yb": True})
    business_logic()
```

reason why,
you have two context managers working. When you send first request, you enter first context manager which checks for available matches and cannot find match for called request and just fails, you even do not reach second context manager
so, you either split your `requests` requests under different mocks or you register everything under the same mock.

**Comment by brno32** [comment]
I understand. I've done the following to achieve what I want, and it works!

Thanks!

```python
import responses
import requests

from decorator import decorator

GOOGLE_URL = "https://www.google.com/"
YOUTUBE_URL = "https://www.youtube.com/"


@decorator
@responses.activate
def mock_google(func, *args, **kwargs):
    responses.add(responses.GET, GOOGLE_URL, json={"success": True})
    return func(*args, **kwargs)


def business_logic():
    response = requests.get(GOOGLE_URL)
    payload = response.json()
    assert payload["success"]
    response = requests.get(YOUTUBE_URL)
    payload = response.json()
    assert payload["success"]


@mock_google
@responses.activate
def test_stuff():
    responses.add(
        responses.Response(method="GET", url=YOUTUBE_URL, json={"success": True})
    )
    business_logic()


@responses.activate
@mock_google
def test_stuff_in_a_different_order():
    responses.add(
        responses.Response(method="GET", url=YOUTUBE_URL, json={"success": True})
    )
    business_logic()
```

**Comment by beliaev-maksim** [comment]
@brno32 
glad it works now!

**Comment by brno32** [comment]
Would you be able to make another recommendation? The following doesn't work

```python
import responses
import requests
from decorator import decorator

GOOGLE_URL = "https://www.google.com/"

@responses.activate
@decorator
def mock_google(func, *args, **kwargs):
    responses.add(responses.GET, GOOGLE_URL, json={"success": True})
    return func(*args, **kwargs)

@mock_google
def test_stuff():
    response = requests.get(GOOGLE_URL)
    payload = response.json()
    assert payload["success"]
```

When the api call is made, `responses` doesn't catch it and a real HTTP request is made to google.com

If I add `responses.activate` to my function `test_stuff`, it'll work, but is there a way to accomplish this by only decorating `mock_google` with `@responses.activate`?

**Comment by brno32** [comment]
This problem seemed to solve itself by upgrading both responses and decorator to their latest version, so never mind. Thanks!
