### ISSUE TITLE
Add ability to get a call by method and URL

### ISSUE THREAD

**Issue by paulnicolet** [getsentry/responses#546]
When mocking a lot of requests, it might not always be desirable to access them by index

* We might not be interested in the calls order
* Adding new calls will shift all indices in assertions

```
responses.add(responses.GET, "http://example.com", body=b"test")
requests.get("http://example.com")

# The two are equivalent
responses.calls[0]
responses.calls.get(responses.GET, "http://example.com")
```

**Comment by beliaev-maksim** [comment]
hi @paulnicolet 

have you tried a solution with a matcher ?
did it work for you?
