### ISSUE TITLE
`py.typed` file not installed by default in setup.cfg

### ISSUE THREAD

**Issue by skylander86** [getsentry/responses#552]
### Describe the bug

mypy returns the following error when type checking our project.

`error: Skipping analyzing "responses": module is installed, but missing library stubs or py.typed marker  [import]`

### Additional context

Using mypy version 0.942 and the master version of responses.

### Version of `responses`

commit 04c9e1545d3413e42123c89a9c9d52f86c7b4a36

### Steps to Reproduce

Run mypy on a project that includes `responses`

```python
import responses

print(responses)
```

### Expected Result

There should be no mypy errors.

### Actual Result

`error: Skipping analyzing "responses": module is installed, but missing library stubs or py.typed marker  [import]`

**Comment by beliaev-maksim** [comment]
we are in progress of migration of all stub files into in-lines
