### ISSUE TITLE
How to get the request body?

### ISSUE THREAD

**Issue by astrike30** [getsentry/responses#561]
I want to be able to make assertions against what was passed as the request body. Am I missing something or is there no way to do this?

Thanks😄

**Comment by beliaev-maksim** [comment]
checking docs ? :)
https://github.com/getsentry/responses#matching-request-body-contents

**Comment by astrike30** [comment]
I understand that I can use a matcher, but for example, I pass a date to the request and I need to make sure that it is in the correct range. I would use the `.assertAlmostEqual` method of the TestCase class traditionally.

**Comment by beliaev-maksim** [comment]
then you can create a custom matcher
https://github.com/getsentry/responses#creating-custom-matcher

**Comment by ThiefMaster** [comment]
Is there any reason why this what I can only call ugly hack is needed to access things as basic as the query string or the body? I would expect to just have access to `urlsplit(mock.url).query` and `mock.body`, but both are empty...

**Comment by beliaev-maksim** [comment]
@ThiefMaster because mock is not the request and response is the same as you get from requests

If you think that response returned doesn't match one from requests lib, please open an issue
