### ISSUE TITLE
Documentation Question / How Do I : retrieve request bodies for previous calls

### ISSUE THREAD

**Issue by jovlinger** [getsentry/responses#571]
Sorry; this doesn't feel like code bug, but perhaps should be made more explicit in the documentation. 

It seems like a rather common use-case, so I'm sure I'm missing something. 

I would like to capture and assert against all of the requests made to a mocked Response object. 

The documentation shows how to retrieve the `call count`, and for dynamic requests, I can see the `calls` attribute.   What I would like to do is to retrieve each call to the Response object in order, and assert against the request body. Is this possible? 

Thanks!

I apologize if this is the wrong forum; no other suggested itself.

**Comment by beliaev-maksim** [comment]
What is about using ordered registry in combination with `matchers`?
Have you considered it?

**Comment by jovlinger** [comment]
No, I hadn't.

I ended up implementing something with callbacks that append the request to
a per-response history list.

I will look into your suggestion; it might be more natural.

Thanks!

**Comment by beliaev-maksim** [comment]
sounds very redundant.
I think the best would be to use `matchers` and just auto assert in case if request body does not match the expected one.

second option would be just to check calls. `responses.calls`
https://github.com/getsentry/responses/blob/d49f82958887b0f55479714319df22a47c4fd3bc/responses/__init__.py#L873

**Comment by jovlinger** [comment]
responses.calls() sounds like exactly what I want.

Thanks!
