### ISSUE TITLE
Incorrect error raised when max retries are exceeded

### ISSUE THREAD

**Issue by jared-duo** [getsentry/responses#572]
### Describe the bug

When testing retry logic a `urllib3.exceptions.MaxRetryError` is raised instead of a `requests.exceptions.RetryError`.

### Version of `responses`

0.21.0

### Steps to Reproduce

```python
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from multiprocessing import Process
from tempfile import TemporaryDirectory
from time import sleep

import pytest
import requests
import responses
from requests.adapters import HTTPAdapter, Retry
from requests.exceptions import RetryError
from responses.registries import OrderedRegistry

_PORT = 8000

_SESSION = requests.session()
_SESSION.mount("http://", HTTPAdapter(max_retries=Retry(1, status_forcelist=[404])))


class CustomException(Exception):
    ...


def get(url: str):
    """System-under-test, catches retry errors and raises custom error"""
    try:
        return _SESSION.get(url)
    except RetryError:
        raise CustomException(url)


@responses.activate(registry=OrderedRegistry)
def test_get_responses():
    """Uses responses - fast, but has a bug"""
    url = f"http://localhost:{_PORT}/does_not_exist"
    rsp1 = responses.get(url, body="Error", status=404)
    rsp2 = responses.get(url, body="Error", status=404)

    with pytest.raises(CustomException):
        get(url)


def test_get_local_server(server: Process):
    """Uses a local server - slow, but correct"""
    url = f"http://localhost:{_PORT}/does_not_exist"
    with pytest.raises(CustomException):
        get(url)


### Fixtures to run a local server which serves 404s for everything but the root path


@pytest.fixture
def server():
    proc = Process(target=_run_server)
    proc.start()
    # Wait for the server to start, otherwise we may get a NewConnectionError as the connections
    # will be refused.
    sleep(1)
    yield proc
    proc.terminate()


def _run_server():
    """Creates a server that serves an empty directory 404'ing anything but the root path"""
    with TemporaryDirectory() as tempd:
        with ThreadingHTTPServer(
            ("", _PORT), lambda *args: SimpleHTTPRequestHandler(*args, directory=tempd)
        ) as httpd:
            httpd.serve_forever()
```

### Expected Result

Both tests pass.  More specifically that responses follows the logic ([original - v2.5.0](https://github.com/psf/requests/blob/v2.5.0/requests/adapters.py#L417-L424), [most recent version - v2.28.1](https://github.com/psf/requests/blob/v2.28.1/requests/adapters.py#L549-L565)) introduced in requests v2.5.0 ([the version that introduced the ability to use urllib3's Retry object with HTTPAdapters](https://github.com/psf/requests/blob/main/HISTORY.md#250-2014-12-01) ) that converts `urllib3.exceptions.MaxRetryError`s into `requests.exceptions` exceptions, specifically `ResponseError`s becoming `RetryError`s.

### Actual Result

The responses based test does not pass, as it raises `urllib3.exceptions.MaxRetryError` instead of a `requests.exceptions.RetryError`.

**Comment by beliaev-maksim** [comment]
we just reraise the error from the `urllib3.Retry` lib.
https://github.com/getsentry/responses/blob/1db612debb0955272bab596be133ed8e912a067e/responses/__init__.py#L1036

basically, exception must include `reason` attribute, to raise `RetryError`, which looks to be not the part of the `urllib3`.

where do they append the reason?

**Comment by jared-duo** [comment]
> we just reraise the error from the urllib3.Retry lib.

Yup, that is the suspected bug/deviation from the behavior of the `requests` module

> where do they append the reason?

It looks like that logic lives in the urllib3 library.  Here is the [basic logic](https://github.com/urllib3/urllib3/blob/26383f7acfcfd631942bbb579f284c0a6ec84f19/src/urllib3/util/retry.py#L510-L512) in the `Retry.increment` method and here is the [caller's logic](https://github.com/urllib3/urllib3/blob/a80c248c34a77e106551bf997e726457b03f42b5/src/urllib3/connectionpool.py#L769-L801) in the `HTTPConnectionPool.urlopen` method.

It appears that any `HTTPException`s (e.g. non-200s listed in the status force list) turn into `ResponseError`s and proxy and ssl errors are more specific.

As [linked](https://github.com/psf/requests/blob/v2.28.1/requests/adapters.py#L549-L565) before the `requests` package does just checks the `reason` that `urllib3` attaches and does not attach a `reason` itself.

**Comment by 1Mark** [comment]
I'm having this exact issue `When testing retry logic a urllib3.exceptions.MaxRetryError is raised instead of a requests.exceptions.RetryError.`

**Comment by beliaev-maksim** [comment]
@1Mark @jared-duo 
please check #575 

should fix the issue
