### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by foxadb** [getsentry/responses#576]
Hello folks,

I really like this contribution https://github.com/getsentry/responses/pull/569 and I would like to use it, but it's not shipped in a release yet.

Do you know when the next release is planned?

Thanks

**Comment by beliaev-maksim** [comment]
We need a bit more time to finish planned features and then will release

**Comment by JesseDeLoore** [comment]
I'd like to second that request for a release.
https://github.com/getsentry/responses/pull/562 and https://github.com/getsentry/responses/pull/569 would make life a lot easier

**Comment by beliaev-maksim** [comment]
Done!
