### ISSUE TITLE
Response library in python give me back a wrong response status code when trying to request a JavaScript file

### ISSUE THREAD

**Issue by malekmahmed** [getsentry/responses#591]
### Describe the bug

Hello,
When I use the response library in python I get the wrong response status code but I get the right one when I use urllib.request

**Code Using Response library:**

```
import requests
try:
    r = requests.head("https://www.codecademy.com/cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible.js")
    print(r.status_code)
    # prints the int of the status code. Find more at httpstatusrappers.com :)
except requests.ConnectionError:
    print("failed to connect")
```

This URL `https://www.codecademy.com/cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible.js` gives me back 404 status code even though it gives me 200 when I visit URL in the browser and I can see the javascript response.

When I used the urllib.request library it gave back the right status code which is 200

**Code Using urllib.request library:**
```
from urllib.request import urlopen
urls = ['https://www.codecademy.com/cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible.js','https://www.codecademy.com/idontexist.js']
results={}
for url in urls:
    try:
        ret = urlopen(url)
        if ret.code == 200:
            state="Exists"
            print(url+' : {}'.format(state))
    except:
        state="Not exists"
        print(url+' : {}'.format(state))

    results[url]=state
```

### Additional context

Maybe there are more situations where this happens than just JavaSript files I didn't try more URLs.

### Version of `responses`

0.21.0

### Steps to Reproduce

1- Go to this URL https://www.codecademy.com/cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible.js in your browser and you will get a 200 response.

2- Run this code and you will get 404 not found
```
import requests
try:
    r = requests.head("https://www.codecademy.com/cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible.js")
    print(r.status_code)
    # prints the int of the status code. Find more at httpstatusrappers.com :)
except requests.ConnectionError:
    print("failed to connect")
```

### Expected Result

The code should have given back a 200 status code.

### Actual Result

The code gives back 404 a status code.

**Comment by beliaev-maksim** [comment]
I don't see a bit of a code where you use responses

May be you wanted to open it against "requests"?
PS
requests is so well written, that I don't think it is an issue on their side
