### ISSUE TITLE
Raising MaxRetryError when should raise RetryError

### ISSUE THREAD

**Issue by jklemm** [getsentry/responses#592]
### Describe the bug

Since `responses` it's to be used as a mock of `requests`, I expect the same behaviours.

Looking for [`requests` code](https://github.com/psf/requests/blob/v2.22.0/requests/adapters.py#L500), dealing with retry, it never raise a `urllib3.exceptions.MaxRetryError`, it threats this error and raises a `requests.exceptions.RetryError` or other exceptions (`ConnectTimeout`, `ProxyError`, `SSLError` or `ConnectionError`).

So, I believe that `responses` should raise an `RetryError` when maximum retry is reached. If don't, the test code needs to expect a `MaxRetryError` while the production code needs to expect a `RetryError`, not cool yeah?

### Version of `responses`

0.21.0

### Steps to Reproduce

This code works on production:

```python
import requests
from requests.adapters import HTTPAdapter
from requests.exceptions import RetryError
from urllib3 import Retry


def execute():
    try:
        session = requests.Session()
        retry = Retry(total=3, status_forcelist=(500, 502, 503, 504), allowed_methods=('GET', 'POST', 'PUT'))
        session.mount('http://', HTTPAdapter(max_retries=retry))
        response = session.request('POST', 'http://httpstat.us/500', json='true', timeout=10)
        return response.content.decode()
    except RetryError:
        raise


if __name__ == '__main__':
    print(execute())
```

But, we can't test it.  It not raise a `RetryError`.

```python
from unittest import TestCase
import responses
from requests.exceptions import RetryError
from requests_retry import execute


class RequestsTests(TestCase):
    @responses.activate
    def test_requests_raises_retry_error(self):
        responses.add('POST', 'http://httpstat.us/500', status=500)

        with self.assertRaises(RetryError):
            execute()
```

### Expected Result

Expect that responses returns a `RetryError`, the same behaviour of `requests`.

### Actual Result

Actually raise a `MaxRetryError`.

```python
from unittest import TestCase
import responses
from requests_retry import execute
from urllib3.exceptions import MaxRetryError


class RequestsTests(TestCase):
    @responses.activate
    def test_requests_raises_retry_error(self):
        responses.add('POST', 'http://httpstat.us/500', status=500)

        with self.assertRaises(MaxRetryError):
            execute()
```

**Comment by beliaev-maksim** [comment]
Hi
Can you reproduce on the latest master?

**Comment by jklemm** [comment]
Hi @beliaev-maksim !

After I open this issue, I see the master code and correct Exception is raised.

This correction comes on next version?

Thanks.

**Comment by beliaev-maksim** [comment]
yes,
will be released around next week

CC: @markstory

**Comment by jklemm** [comment]
Thanks @beliaev-maksim and @markstory
