### ISSUE TITLE
Redundant runtime dependency on types-toml

### ISSUE THREAD

**Issue by stanislavlevin** [getsentry/responses#595]
### Describe the bug

With f431d49021252657e55253c18f0f8493c61e6ae6 `types-toml` is mandatory runtime dependency, while
it's actually typing stub.

### Version of `responses`

0.22.0

### Steps to Reproduce

```python
# your code goes here

```

### Expected Result

There should be no dependency on typing stuff at runtime.

### Actual Result

 There is runtime dependency on types-toml.

**Comment by beliaev-maksim** [comment]
I am -1 on removing it from run time. Users that have installed responses should not bother themselves to install types for toml to work with our project and do a type checking

@markstory 
thoughts?

**Comment by stanislavlevin** [comment]
This can be done with extras (place all the required typing stuff there). If somebody wants to do type checking they can install it (e.g. `responses[typing]`) explicitly. But if a requirement is strict it would be pulled unconditionally ( i.e. I have no choice).

**Comment by markstory** [comment]
Why is this a problem? Is it because you would like to avoid downloading the additional package?

**Comment by beliaev-maksim** [comment]
moved to tomli
