### ISSUE TITLE
Enable `assert_all_requests_are_fired` globally

### ISSUE THREAD

**Issue by johnnymetz** [getsentry/responses#600]
This is a feature request.

### Describe the feature

I like setting `assert_all_requests_are_fired=True` because it ensures I don't have any unused `Response` registerations. I would love to be able to enable this globally so I don't need to pass `assert_all_requests_are_fired=True` to every test.

Is there a way to do this? If not, I'm happy to work on this feature.

### Version of `responses`

0.22.0

### Steps to Reproduce

```python
@responses.activate(assert_all_requests_are_fired)
def test_one():
    pass

@responses.activate(assert_all_requests_are_fired)
def test_two():
    pass
```

### Expected Result

Something like:

```python
responses.ASSERT_ALL_REQUESTS_ARE_FIRED = True

@responses.activate(assert_all_requests_are_fired)
def test_one():
    pass

@responses.activate(assert_all_requests_are_fired)
def test_two():
    pass
```

### Actual Result

-

**Comment by beliaev-maksim** [comment]
You can already do it

https://github.com/getsentry/responses/blob/84afafbf24942be31c6e29827c2c67d7efc16493/CHANGES#L44

**Comment by johnnymetz** [comment]
@beliaev-maksim The link you sent me doesn't provide any information about setting this up. Moreover I wasn't able to get it working after several hours. I tried the following pytest fixture but no luck:

```
import responses

@pytest.fixture(autouse=True)
def responses_assert_all_requests_are_fired():
    responses.mock.assert_all_requests_are_fired = True
```

Can you reopen this ticket and point to a code example or proper documentation?

**Comment by beliaev-maksim** [comment]
Try `responses.mock.assert_all_requests_are_fired  = True` right after the import of responses

If doesn't work, open a new bug

**Comment by antondeliverect** [comment]
@beliaev-maksim this does not work.

**Comment by beliaev-maksim** [comment]
@antondeliverect
Then please open a bug using the form and carefully fill the fields. We will investigate.

Also, please try on the latest master branch
