### ISSUE TITLE
Can't configure Reply to match multiple errors (or even 1)

### ISSUE THREAD

**Issue by robs-nice99** [getsentry/responses#604]
I'm using `responses` for unit tests code using requests and pytest. My problem is very similar to an example, so I just adapted it (original: https://github.com/getsentry/responses#validate-retry-mechanism).

I'm testing some code that should throw a `requests.exceptions.RetryError` after 3 failed attempts.

    @responses.activate(registry=registries.OrderedRegistry)
    def test_max_retries():
        url = "https://example.com"
        rsp1 = responses.get(url, body="Error", status=500)
        rsp2 = responses.get(url, body="Error", status=500)
        rsp3 = responses.get(url, body="Error", status=500)
        # rsp4 = responses.get(url, body="OK", status=200)
    
        session = requests.Session()
    
        adapter = requests.adapters.HTTPAdapter(
            max_retries=Retry(
                total=3,
                backoff_factor=0.1,
                status_forcelist=[500],
                method_whitelist=["GET", "POST", "PATCH"],
            )
        )
        session.mount("https://", adapter)
    
        resp = session.get(url)
    
        assert resp.status_code == 500
        assert rsp1.call_count == 1
        assert rsp2.call_count == 1
        assert rsp3.call_count == 1
        # assert rsp4.call_count == 1

I was expecting this code to pass, or to fail, but not to throw exception from Responses about a missing configuration. What am I doing wrong?

    E           requests.exceptions.ConnectionError: Connection refused by Responses - the call doesn't match any registered mock.
    E           
    E           Request: 
    E           - GET https://example.com/
    E           
    E           Available matches:

**Comment by beliaev-maksim** [comment]
Looks like you exhausted the registry. There is no more entries

**Comment by robs-nice99** [comment]
So I'm doing the math wrong? 3 retries for 3 registries. That's not right?
```
    rsp1 = responses.get(url, body="Error", status=500)
    rsp2 = responses.get(url, body="Error", status=500)
    rsp3 = responses.get(url, body="Error", status=500)

  ....

  ....Retry(total=3,

```

**Comment by beliaev-maksim** [comment]
One request + 3 retries = 4

**Comment by robs-nice99** [comment]
Of course!... The original request is not a retry... 
Thanks! Was looking at this for days...
