### ISSUE TITLE
Type checking `calls[]`

### ISSUE THREAD

**Issue by evilensky** [getsentry/responses#609]
I have this bit of code:

```
        rsps.assert_call_count(
            "https://host/uri",
            1,
        )
        assert rsps.calls[0].request.body == json.dumps( 
            {"data": [{"key": value, "key": "value"}]}
        ).encode("utf-8")
```
(ignoring the smell of the code itself :)  )

which results in this type check failure:

> Cannot access member "request" for type "List[Call]"
  Member "request" is unknown

Is this coming from [this](https://github.com/getsentry/responses/blob/b30c13fe1c9a2e60e7e2de7a92322b4d4ad57562/responses/__init__.py#L246) annotation? Should getitem instead be annotated with a return type that takes into account possible member attributes?

**Comment by beliaev-maksim** [comment]
please open a bug using bug template
