### ISSUE TITLE
Type checking calls[] is insufficient

### ISSUE THREAD

**Issue by evilensky** [getsentry/responses#610]
### Describe the bug

this bit of code

```Python
import requests
import responses

def get_something():
    return requests.get('http://example.com')


def test_get_something():
    with responses.RequestsMock() as rsps:
        rsps.add(responses.GET, 'http://example.com', body='foo')
        foo = get_something()
        assert rsps.calls[0].request.url == 'http://example.com/'
```

results in a type checking failure in mypy and pyright.  The Pyright message is:

```
Cannot access member "request" for type "List[Call]"
  Member "request" is unknown
```

### Version of `responses`

0.22.0

### Steps to Reproduce

Example in bug description.

### Expected Result

The example code should pass type checking. Members of List[Call] should have their attributes properly annotated.

### Actual Result

`
Cannot access member "request" for type "List[Call]"
  Member "request" is unknown
`

**Comment by beliaev-maksim** [comment]
Thanks for reporting an issue

Can you please attach a minimal reproducible code snippet?

Similar to stackoverflow
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by evilensky** [comment]
Got it. I believe the below is both complete and minimal:

```Python
import requests
import responses

def get_something():
    return requests.get('http://example.com')


def test_get_something():
    with responses.RequestsMock() as rsps:
        rsps.add(responses.GET, 'http://example.com', body='foo')
        foo = get_something()
        assert rsps.calls[0].request.url == 'http://example.com/'
```

The mypy equivalent of the above Pyright error is:

`error: Item "List[Call]" of "Union[Call, List[Call]]" has no attribute "request"  [union-attr]`

**Comment by evilensky** [comment]
This was fixed in master? any chance we could get a release? :) https://github.com/getsentry/responses/commit/26bb973e26fe04e39e33a42af7d054e3a607a094

**Comment by beliaev-maksim** [comment]
Yes, we will do it soon

Need to add a couple of things

**Comment by evilensky** [comment]
Any ETA on a new release? Thanks for the great tool.

**Comment by beliaev-maksim** [comment]
@evilensky please track #629 ticket for the release info

Build must pass internal review before publishing, usually a couple of weeks
