### ISSUE TITLE
Ask for forcing the retry policy to be 0

### ISSUE THREAD

**Issue by vilit1** [getsentry/responses#621]
I am currently using the requests mock as so:

``` 
@pytest.fixture
def mocked_response():
    with responses.RequestMock() as rsps:
        yeild rsps
```

With the update from 0.20.0 to 0.21.0 and 0.22.0, the retry mechanism forces our tests to fail. We want to force the retry mechanism to not activate and one way I have come up with is to overwrite the _on_request with a partial function as so:

``` 
@pytest.fixture
def mocked_response():
    with responses.RequestMock() as rsps:
        on_request_with_no_retry = partial(rsps._on_request, retries=Retry(0, read=False))
        rsps._on_request = on_request_with_no_retry
        yeild rsps
```

Is there a cleaner way to do this? I would prefer having the responses.RequestMock() initializer take in either a Retry object or an HttpAdapter (that I can attach the Retry object to).

**Comment by beliaev-maksim** [comment]
please reopen the bug using the form
