### ISSUE TITLE
Store the initial request somewhere

### ISSUE THREAD

**Issue by sshishov** [getsentry/responses#633]
Hi dear developers, I would like to ask how we can access the initial request was made for the caught response?

In the beginning I was thinking that we can access it thought `.request` somehow...

```
rsp = responses.add(method=responses.POST, url='https://example.com/, body='my body content)
...
assert 'some data' in rsp.request.text
```

The question is... how we can assert that the request was done with some specific parameters.
I know that there are `matchers` there but it does not look great to inject some matchers, especially for content inside the responses mock.

I would like to `assert` them separately...

**Comment by beliaev-maksim** [comment]
Overall, we attach the initial request to a response

**Comment by sshishov** [comment]
Hi @beliaev-maksim ,

Could you please show me how I can access it?
Please note that in my test I am calling some other API, which is calling that API internally through the code and I do not have access to the response of that API inside my test. I have access only to the `responses` mock...

Thanks you for the help!

**Comment by beliaev-maksim** [comment]
In such case the best would be to use matchers

But you can explore the CallList object which stores calls history
