### ISSUE TITLE
When will there be a new release to support urllib3>=2 ?

### ISSUE THREAD

**Issue by JohnVillalovos** [getsentry/responses#652]
### Describe the bug

Current release 0.23.1 does not seem to support `urllib3` >= 2.

I see https://github.com/getsentry/responses/commit/071306524af1b4ee1797c45a46525274d271a9b6 which seems like it might resolve that issue but that was merged after the current release.

### Version of `responses`

0.23.1

**Comment by beliaev-maksim** [comment]
@markstory technically, we can release from `master`

**Comment by markstory** [comment]
Started the [release](https://github.com/getsentry/responses/actions/runs/5653402808) process for 0.23.2
