### ISSUE TITLE
Overly strict version constraint on urllib3

### ISSUE THREAD

**Issue by damian-rp** [getsentry/responses#657]
Hello team,

I see that in yesterday's release, you have changed `responses` to require v2.0 of urllib3 or higher.

This is causing us some dependency conflicts, as our projects use other packages that are still running on the v1.0 branch.

I see that urllib3 v1.0 is still being actively maintaned. Is there a specific reason that `responses` can no longer use it? I had a look at the discussions in #635 and #636, which discuss compatibility issues with v3.0, but I don't understand why the minimum version was changed here.

Since `responses` is of course a testing library that we don't install in production, I would opine that it should keep version constraints as loose as possible, so that it accurately tests the version(s) of other packages that would be installed in a production environment. 🙂 Is it possible to get this changed?

**Comment by JohnVillalovos** [comment]
I have proposed PR #659 to allow older versions of `urllib3`. Not sure if it will be accepted or not.

**Comment by bearrito** [comment]
Same. This library is used by Moto which I think is the standard test library for AWS services. That library relies on boto. Boto has a hard constraint for urlib < 1.27
