### ISSUE TITLE
Feature: Simulate timeout of request

### ISSUE THREAD

**Issue by Seluj78** [getsentry/responses#660]
I would like to simulate a timeout on a request with `responses`. Is it possible to do it already ?

**Comment by markstory** [comment]
Have you tried raising a timeout error from you response mock by using a callback? Or using [an exception](https://github.com/getsentry/responses#exception-as-response-body) as the response body?

**Comment by Seluj78** [comment]
Yes it worked with the exception as the body ! Thanks !
