### ISSUE TITLE
headers parameter for responses.add

### ISSUE THREAD

**Issue by hfaran** [getsentry/responses#68]
Would it be possible for `responses.add` to support a `headers` parameter? Having to create a callback just to add headers seems a bit more work than it should be.

**Comment by dcramer** [comment]
I'd +1 this change, but dont have time to do it myself. The code is fairly concise, so if you want to submit a PR I'm happy to provide feedback.

**Comment by hfaran** [comment]
I can do that; should be easy enough.

**Comment by prokaktus** [comment]
@hfaran If I understand correctly, `adding_headers` option is doing exactly what you want - add headers to response:
https://github.com/getsentry/responses/blob/2b5e941657f2ded500af860dd069fb088e9e07f9/responses.py#L132

Maybe, this is should to be put into docs.

**Comment by bittner** [comment]
Even better: There is the `headers` attribute available for that, which works as expected.

Information about that was added to the [README](https://github.com/getsentry/responses#response-parameters) 3 years ago via https://github.com/getsentry/responses/commit/d4ca63336d96a784db257325860dfe8c476d86d1.

Looks like we can close this issue, or is there anything left to do?

**Comment by hfaran** [comment]
This issue is over 5 years old now and I honestly have no idea what I was using this for at the time. This issue can be closed if someone who is a maintainer considers it fixed 🙂
