### ISSUE TITLE
Response count not reset when defining Response outside of test function

### ISSUE THREAD

**Issue by svleeuwen** [getsentry/responses#687]
I prefer to define responses in a separate module outside of test functions.
But then the response.call_count is not reset when the test ends.

Adding copy.copy does fix the issue, but maybe this can be circumvented so I don't have to use that?

Example:
```
import requests
import responses

url = "https://example.com"
response_200_ok = responses.Response("GET", url)

@responses.activate()
def test_one():
    responses.add(response_200_ok)
    requests.get(url)
    assert response_200_ok.call_count == 1

@responses.activate()
def test_two():
    responses.add(response_200_ok)
    requests.get(url)
    assert response_200_ok.call_count == 1  # this fails since the call count is 2
```

Working example:
```
import copy
import requests
import responses

url = "https://example.com"
response_200_ok = responses.Response("GET", url)

@responses.activate()
def test_one():
    r = responses.add(copy.copy(response_200_ok))
    requests.get(url)
    assert r.call_count == 1

@responses.activate()
def test_two():
    r = responses.add(copy.copy(response_200_ok))
    requests.get(url)
    assert r.call_count == 1
```

**Comment by beliaev-maksim** [comment]
I would say that is the desired behavior

you do not need to copy the object, you can set up test class and on teardown or setup of the method initialize the response or reset call count

**Comment by svleeuwen** [comment]
Do you mean by doing something like this?

```
@pytest.fixture(autouse=True)
def reset_response_mocks():
    yield
    response_200_ok.call_count = 0
```

**Comment by beliaev-maksim** [comment]
that is a fixture which technically will work, but I would rather use `class` with setup or teardown method

**Comment by svleeuwen** [comment]
Got it. 

But my main question was, the only way to reset the call count would be to set the `call_count` attribute on every Response instance?

**Comment by beliaev-maksim** [comment]
or on every test you initialize a new object

```py
class Test:
    def setup_method(self):
         self.response_200_ok = responses.Response("GET", url)
    def test1(self):
         r = responses.add(self.response_200_ok )
```

smth like this

**Comment by svleeuwen** [comment]
But my goal is to reuse the same responses in multiple tests.

That's why I started with:
> I prefer to define responses in a separate module outside of test functions.

**Comment by beliaev-maksim** [comment]
then just reset the call counter.
but this is until #664 is merged, then you have to clean up the list
