### ISSUE TITLE
multiple matches in disjunction

### ISSUE THREAD

**Issue by fmieres** [getsentry/responses#709]
Hi! awesome repo! 
Is there a way to accept any of possible matches ? 
Like in an or condition: 
```python
with responses.RequestsMock() as rsps:
    rsps.add(
        responses.POST,
        url,
        json={"error": "OK"},
        match=[
          # any(
            matchers.json_params_matcher(body1),
            matchers.json_params_matcher(body2)
        ],
        status=200,
    )
    yield rsps
```

the currenct code will accept said match if both `body1` and `body2` match

**Comment by beliaev-maksim** [comment]
If you use default registry you can add matchers into separate responses

Then it will iterate until matches

**Comment by fmieres** [comment]
ok, that works. I did that later but just wanted to ask because it might be an improvement. Awesome library. Thanks for all!
