### ISSUE TITLE
Release request 

### ISSUE THREAD

**Issue by ddarricau** [getsentry/responses#714]
Hello,

Following the merge of this [PR](https://github.com/getsentry/responses/pull/712) which fixes this [issue](https://github.com/getsentry/responses/issues/708) into the master branch I am wondering if it is reasonable to ask for a release.

The tests at my company depend heavily on that issue being fixed. So I would like to offer my help if you need any for the release process (testing, reviewing, etc ...)

Thanks again,
Didier

**Comment by markstory** [comment]
I started a release, but our tooling had some issues. I'll need to figure out what is wrong with the release tooling.

**Comment by FelixSchwarz** [comment]
Also I noticed that pypi currently does not have 0.25.1. It would be nice if new releases were uploaded to pypi as well.

**Comment by markstory** [comment]
> Also I noticed that pypi currently does not have 0.25.1. It would be nice if new releases were uploaded to pypi as well.

Yeah, I did that release incorrectly so no packages were published. For compliance reasons I have to use our release tooling to publish packages to pypi, and that release tooling is having troubles.

**Comment by amercader** [comment]
Just wondering if the release tooling is behaving again? we are stuck with urlib3>2 and can't get the test suite working with the current version of responses. Many thanks!

**Comment by amercader** [comment]
Thanks @markstory
