### ISSUE TITLE
pylint no-member error

### ISSUE THREAD

**Issue by jtprince** [getsentry/responses#74]
Every function on responses ends up with a pylint error.  Can the import be done differently in responses to avoid this?  Is this a problem with pylint?  I know that numpy had similar issues with pylint but those were eventually solved (not sure how).

What follows is a code snippet, then the pylint error after it.  I'm using the latest pylint, 1.4.4, and latest responses 0.4.0.

``` python
@responses.activate
    def test_form_submit(self):

(E1101-no-member) Module 'responses' has no 'activate' member-SubmitFormTest.test_form_submit

responses.add(
            responses.POST,
            url=re.compile(r'https://forms.hubspot.com/uploads/form/v2/'),
            body='',
            status=204,
            content_type='application/json',
        )


(E1101-no-member) Module 'responses' has no 'add' member-SubmitFormTest.test_form_submit
(E1101-no-member) Module 'responses' has no 'POST' member-SubmitFormTest.test_form_submit

content_type = responses.calls[0].request.headers.get('content-type')

(E1101-no-member) Module 'responses' has no 'calls' member-SubmitFormTest.test_form_submit
```

**Comment by dcramer** [comment]
We can manually build the functions but it will require more effort to maintain. tbh this is pylint's problem

**Comment by mikekreuzer** [comment]
[TYPECHECK]
ignored-classes= responses

in .pylintrc is the workaround I'm using

**Comment by acannon828** [comment]
Should a bug report be filed with the pylint project?

**Comment by Enforcer** [comment]
I understand argumentation behind keeping these function dynamically generated, but this stands at odds with SCA, like linters/mypy/type annotations. Perhaps this inconvenience could be resolved using typeshedding. I could invest some time and prepare appopriate .pyi file if that's feasible. Would you accept such a contribution? @markstory @dcramer

**Comment by markstory** [comment]
If there was also changes to CI tooling to ensure the pyi doesn't drift from the actual implementation I would be ok with that.

**Comment by beliaev-maksim** [comment]
@markstory 
I think this one could be closed, now we have stub files and should work. Here is the test with latest HEAD and latest `pylint`

![image](https://user-images.githubusercontent.com/51964909/140055201-4c5ed22f-c1a2-47d4-b1f3-3bfebcffba39.png)


code from `lint.py`
~~~python
"""
hey
"""
import requests
import responses


@responses.activate
def test():
    """
    My test
    """
    def validation_callback(_):
        return 200, {}, b'custom_name'

    url = 'https://some.test.url'
    responses.add_callback(
        responses.GET,
        url,
        callback=validation_callback,
    )

    resp = requests.get(url)
    print("\n" + str(resp) + "\n")
    print(resp.content)


test()
~~~

**Comment by jtprince** [comment]
Closing based on [this comment](https://github.com/getsentry/responses/issues/74#issuecomment-958961167).

**Comment by beliaev-maksim** [comment]
@jtprince 
thanks!
