### ISSUE TITLE
Set default params for all responses.add within TestCase

### ISSUE THREAD

**Issue by pnuckowski** [getsentry/responses#75]
Hello,

I have some idea for new feature in `responses`

it would be really nice to have option to set global (within TestCase) kwargs for `responses.add`.

Currently to testing the same endpoint within TestCase I have a lot of boilerplate code.

``` python
@responses.activate
def test_resp_200(self):
    responses.add(responses.GET, 'http://twitter.com/api/1/foobar',
                  body='', status=200,
                  content_type='application/json')

    response = requests.get('http://example.com')
    self.assertEqual(response.status_code, 200)

@responses.activate
def test_resp_400(self):
    responses.add(responses.GET, 'http://twitter.com/api/1/foobar',
                  body='', status=400,
                  content_type='application/json')

    response = requests.get('http://example.com')
    self.assertEqual(response.status_code, 400)
```

Only difference in those tests is `status`....

To remove some boilerplate code I write decorator, lets say `mock_response` which call `responses.add` with "default" values. To overwrite those default values I pass additional kwargs from decorator to `responses.add`

Let assume that default status code is 200, but for specific `test_*` I want code 400.
Same tests as above but with default options...

``` python
@responses.activate
@mock_response()  # responses.mock()
def test_resp_200(self):
    response = requests.get('http://example.com')
    self.assertEqual(response.status_code, 200)

@responses.activate
@mock_response(status=400)  # responses.mock()
def test_resp_400(self):
    response = requests.get('http://example.com')
    self.assertEqual(response.status_code, 400)
```

It look more beautiful and elegant.

To set "global" params it could be class decorator or metaclass.

AC:
- setting global params (by decorator or metaclass) and manually call `responses.add` did not raise any exception, also registering new endpoint are still possible (for more complex test cases).
- test method decorator `mock_response` should not be used without "global"/test class decorator

Possible names and example:

``` python
responses.default(params=params)
class FooTestCase(TestCase):

    @responses.activate
    @responses.mock(status=400)
    def test_resp_400():
        # act
        # assert

```

`responses.default` - could also have some own arguments. I saw opened issue to apply `responses.activate` to each method that starts from 'test_', it could be good starting point :) 

Additionally `responses.mock` could update default params and call `responses.activate`

What do You think guys, would it be useful??

PS. I would love to implement this and create Pull Request.

**Comment by beliaev-maksim** [comment]
I think proposed idea will produce some implicit behavior 
you can just create a function, that will add 404 status. Call to it is explicit.

so, I am -1 on the idea to implement it

@markstory, 
your thoughts?
if not worth implementation, then lets close the issue
 

~~~python
def add_404(*args, **kwargs):
    kwargs["status"] = 404
    responses.add(*args, **kwargs)


@responses.activate
def test_file():

    url = "http://example.com/"
    add_404(responses.GET, url)
    resp = requests.get(url)

    print("\ncode is: {}".format(resp.status_code))

~~~

**Comment by markstory** [comment]
I agree having responses maintain state creates more opportunity for that state to be wrong as we'll need ways to control how long that state is retained. If you end up with more boilerplate in your tests than you'd like you can either use pytest fixtures, or wrapper functions that let you encapsulate the duplication that you don't want.
