### ISSUE TITLE
Querystring not matched

### ISSUE THREAD

**Issue by dgouldin** [getsentry/responses#78]
Using requests 2.7.0 and responses 0.4.0, it doesn't look like responses is correctly matching querystrings. Example:
```python
import requests
import responses

with responses.RequestsMock(assert_all_requests_are_fired=False) as rsps:
    url = 'http://example.com/foo?bar=1'
    rsps.add(responses.GET, url, status=200)

    # raises ConnectionError
    requests.get(url)
```

The example works if you remove the querystring from the url.

**Comment by dcramer** [comment]
I'm not entirely sure why we have the API this way, but you need to pass match_querystring=True to the rsps.add() call
