### ISSUE TITLE
Feature request: easy assertions on post data

### ISSUE THREAD

**Issue by alexpdp7** [getsentry/responses#79]
``` python
@responses.activate
def foo():
        responses.add(responses.POST, 'http://foo.bar')
        requests.post('http://foo.bar', {'qux': 'quux'})
```

I would like to assert that I've posted qux=quux, but doing this completely well is uncomfortable (esp. if you want to be py2-3 compatible).

Ideally, I would like to do:

``` python
assert responses.calls[0].data = {'qux': 'quux'}
```

or something equivalent.

**Comment by danield-hyprbrands** [comment]
+1

**Comment by greenmoon55** [comment]
+1

**Comment by alexntt** [comment]
Any chance of merging @alexanderyoung's PR? I've come across another instance where I wish this was done

**Comment by berinhard** [comment]
Same here!

**Comment by rdrey** [comment]
Would be nice if it could "match" on body params. That way it would raise if different params were sent (nothing matched).

**Comment by dcramer** [comment]
This is possible today, and while we could add a million new APIs, I'm closing this to avoid noise.

```
    assert responses.calls[0].response.text == '{"value": 6}'
    assert (
        responses.calls[0].response.headers['request-id'] ==
        '728d329e-0e86-11e4-a748-0c84dc037c13'
    )
```
