### ISSUE TITLE
Add ability to force exact match for query strings

### ISSUE THREAD

**Issue by cash** [getsentry/responses#9]
The current comparison uses re.match() so that http://example.com?test=1&foo=bar matches to http://example.com?test=1. Was this done on purpose?

An alternative API would be to allow developers to pass a regex for the url. This could even be auto detected so that it is not escaped like currently:

``` python
            if match['match_querystring']:
                if not re.match(re.escape(match['url']), url):
                    continue
```

**Comment by beliaev-maksim** [comment]
@markstory,
I think this one could be closed as current version will work properly
