### ISSUE TITLE
Python 3.6-dev compability

### ISSUE THREAD

**Issue by jsstylos** [getsentry/responses#90]
Use of `getargspec` causes test cases that use responses to fail:

`3.6-dev/lib/python3.6/site-packages/responses.py:65: in get_wrapped
    args, a, kw, defaults = inspect.getargspec(func)
E   AttributeError: module 'inspect' has no attribute 'getargspec'`

**Comment by prokaktus** [comment]
@jsstylos it should works now
https://bugs.python.org/issue25486

**Comment by markstory** [comment]
Closing as tests are passing in both 3.6 & 3.7 now.
