### ISSUE TITLE
Context do not split with py.test

### ISSUE THREAD

**Issue by item4** [getsentry/responses#91]
I will show you real my codes because I **do not know** how I can reproduce this bugs in simple case.

1. order of test
--------------------

If I change order of [test_too_many_login_tried](https://github.com/item4/ugoira/blob/master/tests/cli_test.py#L40) and [test_invalid_password](https://github.com/item4/ugoira/blob/httpretty/tests/cli_test.py#L82) each other, this test will be broken because `test_too_many_login_tried`'s `'https://www.secure.pixiv.net/login.php'` access must going to `'https://example.com/'` in test `test_invalid_password`.

2. toss and toss and toss again
------------------------------------------

In [test_login_valid](https://github.com/item4/ugoira/blob/master/tests/lib_test.py#L11), I must insert this.

```py3
     responses.add(**{
            'method': responses.POST,
            'url': 'http://example.com',
            'body': '????',
            'content_type': 'text/html; charset=utf-8',
            'status': 301,
            'adding_headers': {
                'Location': 'http://www.pixiv.net/'
            },
        })
```

If I remove it, test will be broken. `'http://example.com'` mentioned in before test, [cli_test.py](https://github.com/item4/ugoira/blob/master/tests/cli_test.py)

---

What the hell?

**Comment by dcramer** [comment]
Responses doesn't know or care about your order of tests. It clears the buffer using a context manager so:

```
# buffer is empty
@responses.activate
def foo():
  # buffer is available
  responses.add('bar')
  # buffer has content

foo()
# buffer is empty
```

if something is broken here it's unlikely to be responses.

**Comment by item4** [comment]
Oh, I see your comment and I re-think cause, and I find some points.

1. requests `Session` save the cache about redirection url (`requests.sessions.Session.redirect_cache`)
2. Any mock lib do not support clean it automatically.
3. I reused Session for keep context in program. but it effect to tests context

I'm sorry and thanks!
