### ISSUE TITLE
reponses requires coverage < 4.0.0 but many systems ships coverage >= 4.0.0

### ISSUE THREAD

**Issue by Germano0** [getsentry/responses#95]
I am following a procedure that will bring responses inside official Fedora repositories.
[responses][1] needs coverage < 4.0.0 but Fedora 23 ships coverage 4.0.3, so during RPM package creation, when the system runs checks/tests I obtain errors
```bash
Traceback (most recent call last):
  File "setup.py", line 94, in <module>
    'Topic :: Software Development'
  File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.4/site-packages/setuptools/command/test.py", line 134, in run
    self.distribution.fetch_build_eggs(self.distribution.tests_require)
  File "/usr/lib/python3.4/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 836, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1074, in best_match
    dist = working_set.find(req)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 711, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (coverage 4.0.3 (/usr/lib64/python3.4/site-packages), Requirement.parse('coverage<4.0.0,>=3.7.1'))
```

Is there anything we can do?

[1]: https://github.com/getsentry/responses/blob/master/setup.py#L33

**Comment by dcramer** [comment]
Personally I strongly disagree with packaging Python libraries with distros. The dependency hell that I've seen requests go through, along with the obvious fact that it simply doesnt work due to Python not supporting multiple lib versions, makes me very much against the pattern.

With that said, if you want to put the effort into ensuring it works with both coverage 3.x as well as 4.x, I'm not against bumping the requirements here.

**Comment by AdamWill** [comment]
Regardless your opinions about distribution packaging (I'd love to know how you think a distribution should write any of its core code in python if it can't package any libraries...), 'pinning' dependencies to outdated versions in this way is hardly a viable long-term strategy. It's not as if upstream coverage is supporting multiple major release series, they're not cutting 3.x releases or supporting them any more.

**Comment by AdamWill** [comment]
FWIW, if I simply drop the "< 4.0.0" constraint and run `python setup.py test` and `python3 setup.py test` on current Fedora Rawhide, both work fine; so at least python 2.7 and python 3.5.1 with coverage 4.1.0-beta1 work fine.

**Comment by dcramer** [comment]
@AdamWill we dont need to support 3.2 -- if you want to submit a PR with the change we can get it in. I'd prefer to keep it still version locked, but coverage.py has historically been good so im ok with saying <5.0

**Comment by AdamWill** [comment]
OK, thanks, I'll submit a PR and we'll see how the travis run goes.
