### ISSUE TITLE
Feature request: response depending on invocation index

### ISSUE THREAD

**Issue by marekyggdrasil** [getsentry/responses#99]
It could be interesting to be able to program different response at second, third, fourth.. call such as:

``` python
responses.add(responses.GET, 'http://twitter.com/api/1/foobar', json={"msg": "not found"}, status=404)
responses.add(responses.GET, 'http://twitter.com/api/1/foobar', json={"msg": "OK"}, status=200)
responses.add(responses.GET, 'http://twitter.com/api/1/foobar', json={"msg": "OK"}, status=200)
responses.add(responses.GET, 'http://twitter.com/api/1/foobar', json={"msg": "not found"}, status=404)
print requests.get('http://twitter.com/api/1/foobar')
print requests.get('http://twitter.com/api/1/foobar')
print requests.get('http://twitter.com/api/1/foobar')
print requests.get('http://twitter.com/api/1/foobar')
```

Expected standard output:

```
<Response [404]>
<Response [200]>
<Response [200]>
<Response [404]>
```

Explanation: If we add response to same URL we simply specify the next response.

Just like it is done in PHP using PHPUnit, provided with [that](https://phpunit.de/manual/current/en/test-doubles.html)

Refer to `Table 9.1. Matchers`, quoting 

<img width="1230" alt="screen shot 2016-01-27 at 4 52 21 pm" src="https://cloud.githubusercontent.com/assets/8202674/12608305/5e6c6b34-c516-11e5-999f-4ac5735fc024.png">

For not the only way I see to reproduce such behaviour is using callback with counter which is a global variable, and it doesn't seem to be elegant way to do it.

``` python
global call

@responses.activate
def test():
    global call
    call = 0
    def request_callback(request):
        global call
        headers = {'key': 'value'}
        if call == 0 :
            call = 1
            return (404, headers, '{"msg": "not found"}')
        elif call == 1 :
            call = 0
            return (200, headers, '{"msg": "ok"}')
    responses.add_callback(responses.GET, 'http://twitter.com/api/1/foobar', callback=request_callback)
    print requests.get('http://twitter.com/api/1/foobar')
    print requests.get('http://twitter.com/api/1/foobar')
```

**Comment by AlJohri** [comment]
this is definitely something that I'd be interested in :+1:

**Comment by chronossc** [comment]
I'm really missing that. :+1:

**Comment by jclark360** [comment]
👍  same here.

**Comment by joscarsson** [comment]
Wouldn't the behavior you're after be possible if using the [`assert_all_requests_are_fired` flag](https://github.com/getsentry/responses#assertions-on-declared-responses)? That flag drops the response from the list when there's a match, and I think the next request would then get the next response.
